"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "syllable-sdk"
__version__: str = "0.35.40"
__openapi_doc_version__: str = "0.0.2"
__gen_version__: str = "2.656.5"
__user_agent__: str = "speakeasy-sdk/python 0.35.40 2.656.5 0.0.2 syllable-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
