"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class A2pMessagingPathCheckRequestTypedDict(TypedDict):
    r"""Body to check US A2P / Messaging Service setup for one number on the Twilio channel."""

    phone: str
    r"""E.164 phone number exactly as Twilio stores it for this incoming number."""


class A2pMessagingPathCheckRequest(BaseModel):
    r"""Body to check US A2P / Messaging Service setup for one number on the Twilio channel."""

    phone: str
    r"""E.164 phone number exactly as Twilio stores it for this incoming number."""
