"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from syllable_sdk.utils import FieldMetadata
from typing_extensions import Annotated, NotRequired, TypedDict


class BodyOrganizationsDeleteTypedDict(TypedDict):
    delete_comments: NotRequired[Nullable[str]]
    r"""Comments explaining the deletion"""


class BodyOrganizationsDelete(BaseModel):
    delete_comments: Annotated[OptionalNullable[str], FieldMetadata(form=True)] = UNSET
    r"""Comments explaining the deletion"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["delete_comments"])
        nullable_fields = set(["delete_comments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
