"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemas_cortex_v1_bridge_phrases_bridgephrasemessages import (
    SchemasCortexV1BridgePhrasesBridgePhraseMessages,
    SchemasCortexV1BridgePhrasesBridgePhraseMessagesTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class BridgePhrasesConfigTypedDict(TypedDict):
    r"""Configuration for conversational bridge phrases.

    Top-level fields are the default (English) phrases.
    The `localized` dict provides per-language overrides keyed by BCP-47 language tag.
    """

    messages: NotRequired[List[str]]
    r"""Unified ordered bridge phrases. If empty, legacy fields are used."""
    randomize_messages: NotRequired[bool]
    r"""When true, unified messages are played in randomized no-repeat cycles. Ignored when unified messages are disabled."""
    first_slow_messages: NotRequired[List[str]]
    r"""Messages to say when the agent is first delayed."""
    very_slow_messages: NotRequired[List[str]]
    r"""Messages to say when the agent is significantly delayed."""
    tool_responses: NotRequired[List[str]]
    r"""Messages to say when a tool call is in progress."""
    localized: NotRequired[
        Dict[str, SchemasCortexV1BridgePhrasesBridgePhraseMessagesTypedDict]
    ]
    r"""Per-language overrides keyed by BCP-47 tag (e.g. \"es-US\")."""
    smart_turn_timeout_seconds: NotRequired[Nullable[float]]
    r"""Seconds of caller silence before injecting the first bridge phrase. Subsequent sleep intervals are 2x, 3x, 4x this base. When unset, the service-wide default applies."""


class BridgePhrasesConfig(BaseModel):
    r"""Configuration for conversational bridge phrases.

    Top-level fields are the default (English) phrases.
    The `localized` dict provides per-language overrides keyed by BCP-47 language tag.
    """

    messages: Optional[List[str]] = None
    r"""Unified ordered bridge phrases. If empty, legacy fields are used."""

    randomize_messages: Optional[bool] = False
    r"""When true, unified messages are played in randomized no-repeat cycles. Ignored when unified messages are disabled."""

    first_slow_messages: Optional[List[str]] = None
    r"""Messages to say when the agent is first delayed."""

    very_slow_messages: Optional[List[str]] = None
    r"""Messages to say when the agent is significantly delayed."""

    tool_responses: Optional[List[str]] = None
    r"""Messages to say when a tool call is in progress."""

    localized: Optional[Dict[str, SchemasCortexV1BridgePhrasesBridgePhraseMessages]] = (
        None
    )
    r"""Per-language overrides keyed by BCP-47 tag (e.g. \"es-US\")."""

    smart_turn_timeout_seconds: OptionalNullable[float] = UNSET
    r"""Seconds of caller silence before injecting the first bridge phrase. Subsequent sleep intervals are 2x, 3x, 4x this base. When unset, the service-wide default applies."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "messages",
                "randomize_messages",
                "first_slow_messages",
                "very_slow_messages",
                "tool_responses",
                "localized",
                "smart_turn_timeout_seconds",
            ]
        )
        nullable_fields = set(["smart_turn_timeout_seconds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
