"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lib_database_dao_organization_bridge_phrases_dao_bridgephrasemessages import (
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages,
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessagesTypedDict,
)
from .toolbridgephraseconfig import (
    ToolBridgePhraseConfig,
    ToolBridgePhraseConfigTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BridgePhrasesConfigPayloadTypedDict(TypedDict):
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """

    phrases: NotRequired[
        LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessagesTypedDict
    ]
    r"""Bridge phrase messages for a single scope (default or one tool)."""
    tools: NotRequired[List[ToolBridgePhraseConfigTypedDict]]
    r"""Per-tool phrase overrides."""
    smart_turn_timeout_seconds: NotRequired[Nullable[float]]
    r"""Seconds of caller silence before injecting the first bridge phrase. Defaults to 2.75s when omitted on write."""
    randomize_bridge_phrases: NotRequired[bool]
    r"""Whether to randomize the order of bridge phrases. When true, the order of the bridge phrases is randomized for each call."""


class BridgePhrasesConfigPayload(BaseModel):
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """

    phrases: Optional[
        LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages
    ] = None
    r"""Bridge phrase messages for a single scope (default or one tool)."""

    tools: Optional[List[ToolBridgePhraseConfig]] = None
    r"""Per-tool phrase overrides."""

    smart_turn_timeout_seconds: OptionalNullable[float] = UNSET
    r"""Seconds of caller silence before injecting the first bridge phrase. Defaults to 2.75s when omitted on write."""

    randomize_bridge_phrases: Optional[bool] = False
    r"""Whether to randomize the order of bridge phrases. When true, the order of the bridge phrases is randomized for each call."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "phrases",
                "tools",
                "smart_turn_timeout_seconds",
                "randomize_bridge_phrases",
            ]
        )
        nullable_fields = set(["smart_turn_timeout_seconds"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
