"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class BridgePhrasesProperties(str, Enum):
    r"""Names of bridge phrases fields supported for filtering/sorting on list endpoint."""

    NAME = "name"
    DESCRIPTION = "description"
    UPDATED_AT = "updated_at"
    LAST_UPDATED_BY = "last_updated_by"
