"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bridgephrasesconfigpayload import (
    BridgePhrasesConfigPayload,
    BridgePhrasesConfigPayloadTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BridgePhrasesCreateRequestTypedDict(TypedDict):
    r"""Request model to create a bridge phrases config."""

    name: str
    r"""The name of the bridge phrases config."""
    description: NotRequired[Nullable[str]]
    r"""Description of the bridge phrases config."""
    config: NotRequired[BridgePhrasesConfigPayloadTypedDict]
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """
    is_default: NotRequired[bool]
    r"""Whether this config should be marked as the default for its suborg. At most one non-deleted config per suborg may be the default; the API returns a 400 if a second default is requested while another is already set."""


class BridgePhrasesCreateRequest(BaseModel):
    r"""Request model to create a bridge phrases config."""

    name: str
    r"""The name of the bridge phrases config."""

    description: OptionalNullable[str] = UNSET
    r"""Description of the bridge phrases config."""

    config: Optional[BridgePhrasesConfigPayload] = None
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """

    is_default: Optional[bool] = False
    r"""Whether this config should be marked as the default for its suborg. At most one non-deleted config per suborg may be the default; the API returns a 400 if a second default is requested while another is already set."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "config", "is_default"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
