"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bridgephrasesagentinfo import (
    BridgePhrasesAgentInfo,
    BridgePhrasesAgentInfoTypedDict,
)
from .bridgephrasesconfigpayload import (
    BridgePhrasesConfigPayload,
    BridgePhrasesConfigPayloadTypedDict,
)
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BridgePhrasesResponseTypedDict(TypedDict):
    r"""Response model for bridge phrases operations.

    A bridge phrases config is a named, sub-org-scoped collection of default bridge
    phrases plus optional per-tool and per-language overrides that can be linked to an
    agent. For more information, see
    [Console docs](https://docs.syllable.ai/Resources/BridgePhrases).
    """

    name: str
    r"""The name of the bridge phrases config."""
    id: int
    r"""The ID of the bridge phrases config to update."""
    updated_at: datetime
    r"""Timestamp of the last update."""
    last_updated_by: str
    r"""Email of the user who last updated this config."""
    description: NotRequired[Nullable[str]]
    r"""Description of the bridge phrases config."""
    config: NotRequired[BridgePhrasesConfigPayloadTypedDict]
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """
    is_default: NotRequired[bool]
    r"""Whether this config is currently marked as the default for its suborg."""
    edit_comments: NotRequired[Nullable[str]]
    r"""Comments for the most recent edit."""
    agents_info: NotRequired[Nullable[List[BridgePhrasesAgentInfoTypedDict]]]
    r"""IDs and names of the agents linked to this bridge phrases config."""


class BridgePhrasesResponse(BaseModel):
    r"""Response model for bridge phrases operations.

    A bridge phrases config is a named, sub-org-scoped collection of default bridge
    phrases plus optional per-tool and per-language overrides that can be linked to an
    agent. For more information, see
    [Console docs](https://docs.syllable.ai/Resources/BridgePhrases).
    """

    name: str
    r"""The name of the bridge phrases config."""

    id: int
    r"""The ID of the bridge phrases config to update."""

    updated_at: datetime
    r"""Timestamp of the last update."""

    last_updated_by: str
    r"""Email of the user who last updated this config."""

    description: OptionalNullable[str] = UNSET
    r"""Description of the bridge phrases config."""

    config: Optional[BridgePhrasesConfigPayload] = None
    r"""The `config` JSONB payload stored on a bridge_phrases row.

    Holds the default phrases plus an inline list of per-tool overrides, each with
    optional per-language (`localized`) overrides. Mirrors the shape documented in
    docs/bridge-phrases-table-migration.md §5.2.
    """

    is_default: Optional[bool] = False
    r"""Whether this config is currently marked as the default for its suborg."""

    edit_comments: OptionalNullable[str] = UNSET
    r"""Comments for the most recent edit."""

    agents_info: OptionalNullable[List[BridgePhrasesAgentInfo]] = UNSET
    r"""IDs and names of the agents linked to this bridge phrases config."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["description", "config", "is_default", "edit_comments", "agents_info"]
        )
        nullable_fields = set(["description", "edit_comments", "agents_info"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
