"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .caseexpression import CaseExpression, CaseExpressionTypedDict
from .celexpression import CelExpression, CelExpressionTypedDict
from .jmespathexpression import JMESPathExpression, JMESPathExpressionTypedDict
import pydantic
from pydantic import Discriminator, Tag
from syllable_sdk.types import BaseModel
from syllable_sdk.utils import get_discriminator
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


From1TypedDict = TypeAliasType(
    "From1TypedDict", Union[CelExpressionTypedDict, JMESPathExpressionTypedDict]
)


From1 = Annotated[
    Union[
        Annotated[CelExpression, Tag("cel")],
        Annotated[JMESPathExpression, Tag("jmespath")],
        Annotated[JMESPathExpression, Tag("jp")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


From2TypedDict = TypeAliasType(
    "From2TypedDict", Union[CaseExpressionTypedDict, From1TypedDict, str]
)
r"""Expression evaluated against the parsed tool response body (the JSON the external tool returned). Supported forms: (1) JMESPath string (default for plain strings) — a bare field name for raw passthrough, or a boolean/computed expression for derived values, (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}."""


From2 = TypeAliasType("From2", Union[CaseExpression, From1, str])
r"""Expression evaluated against the parsed tool response body (the JSON the external tool returned). Supported forms: (1) JMESPath string (default for plain strings) — a bare field name for raw passthrough, or a boolean/computed expression for derived values, (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}."""


class CallResultSaveMappingTypedDict(TypedDict):
    r"""One field-extraction mapping applied to a call action's tool response.

    Example: {\"from\": \"is_valid\", \"to\": \"is_valid\"}
    Example (derived value): {\"from\": \"status == 'valid'\", \"to\": \"is_valid\"}
    """

    from_: From2TypedDict
    r"""Expression evaluated against the parsed tool response body (the JSON the external tool returned). Supported forms: (1) JMESPath string (default for plain strings) — a bare field name for raw passthrough, or a boolean/computed expression for derived values, (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}."""
    to: str
    r"""Workflow variable name to store the extracted value under."""


class CallResultSaveMapping(BaseModel):
    r"""One field-extraction mapping applied to a call action's tool response.

    Example: {\"from\": \"is_valid\", \"to\": \"is_valid\"}
    Example (derived value): {\"from\": \"status == 'valid'\", \"to\": \"is_valid\"}
    """

    from_: Annotated[From2, pydantic.Field(alias="from")]
    r"""Expression evaluated against the parsed tool response body (the JSON the external tool returned). Supported forms: (1) JMESPath string (default for plain strings) — a bare field name for raw passthrough, or a boolean/computed expression for derived values, (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}."""

    to: str
    r"""Workflow variable name to store the extracted value under."""


try:
    CallResultSaveMapping.model_rebuild()
except NameError:
    pass
