"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .callresult import CallResult, CallResultTypedDict
from .caseexpression import CaseExpression, CaseExpressionTypedDict
from .celexpression import CelExpression, CelExpressionTypedDict
from .jmespathexpression import JMESPathExpression, JMESPathExpressionTypedDict
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import AfterValidator
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from syllable_sdk.utils import get_discriminator, validate_const
from typing import Any, Dict, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


CallActionIf1TypedDict = TypeAliasType(
    "CallActionIf1TypedDict", Union[CelExpressionTypedDict, JMESPathExpressionTypedDict]
)


CallActionIf1 = Annotated[
    Union[
        Annotated[CelExpression, Tag("cel")],
        Annotated[JMESPathExpression, Tag("jmespath")],
        Annotated[JMESPathExpression, Tag("jp")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


CallActionIf2TypedDict = TypeAliasType(
    "CallActionIf2TypedDict",
    Union[CaseExpressionTypedDict, CallActionIf1TypedDict, str],
)
r"""Condition to decide whether this item executes. Supported expression forms: (1) JMESPath string (default for plain strings), (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}. Example JMESPath string: \"inputs.can_sign_consent == `true`\"."""


CallActionIf2 = TypeAliasType(
    "CallActionIf2", Union[CaseExpression, CallActionIf1, str]
)
r"""Condition to decide whether this item executes. Supported expression forms: (1) JMESPath string (default for plain strings), (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}. Example JMESPath string: \"inputs.can_sign_consent == `true`\"."""


class CallActionTypedDict(TypedDict):
    name: str
    r"""The name of the tool to call."""
    if_: NotRequired[Nullable[CallActionIf2TypedDict]]
    r"""Condition to decide whether this item executes. Supported expression forms: (1) JMESPath string (default for plain strings), (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}. Example JMESPath string: \"inputs.can_sign_consent == `true`\"."""
    action: Literal["call"]
    arguments: NotRequired[Nullable[Dict[str, Any]]]
    r"""Optional arguments to pass to the tool (supports template strings)"""
    result: NotRequired[Nullable[CallResultTypedDict]]
    r"""Optional deterministic result-capture configuration. When present, selected fields from the tool response are saved into workflow state, so later transitions/conditions/validations can branch on them without the model re-deriving them from tool call history. Currently applied only when the call is routed in inject mode (arguments already complete); hinted/routed calls are not yet supported."""


class CallAction(BaseModel):
    name: str
    r"""The name of the tool to call."""

    if_: Annotated[OptionalNullable[CallActionIf2], pydantic.Field(alias="if")] = UNSET
    r"""Condition to decide whether this item executes. Supported expression forms: (1) JMESPath string (default for plain strings), (2) typed JMESPath object {\"type\":\"jp\"|\"jmespath\",\"expression\":\"...\"}, or (3) typed CEL object {\"type\":\"cel\",\"expression\":\"...\"}. Example JMESPath string: \"inputs.can_sign_consent == `true`\"."""

    ACTION: Annotated[
        Annotated[Optional[Literal["call"]], AfterValidator(validate_const("call"))],
        pydantic.Field(alias="action"),
    ] = "call"

    arguments: OptionalNullable[Dict[str, Any]] = UNSET
    r"""Optional arguments to pass to the tool (supports template strings)"""

    result: OptionalNullable[CallResult] = UNSET
    r"""Optional deterministic result-capture configuration. When present, selected fields from the tool response are saved into workflow state, so later transitions/conditions/validations can branch on them without the model re-deriving them from tool call history. Currently applied only when the call is routed in inject mode (arguments already complete); hinted/routed calls are not yet supported."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["if", "action", "arguments", "result"])
        nullable_fields = set(["if", "arguments", "result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CallAction.model_rebuild()
except NameError:
    pass
