"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .callresultsavemapping import CallResultSaveMapping, CallResultSaveMappingTypedDict
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CallResultTypedDict(TypedDict):
    r"""Deterministic result-capture configuration for a call action's tool response."""

    save: NotRequired[List[CallResultSaveMappingTypedDict]]
    r"""Field mappings extracted from the tool response into workflow state."""


class CallResult(BaseModel):
    r"""Deterministic result-capture configuration for a call action's tool response."""

    save: Optional[List[CallResultSaveMapping]] = None
    r"""Field mappings extracted from the tool response into workflow state."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["save"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
