"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class CardClickResponseTypedDict(TypedDict):
    status: str
    r"""The outcome of the request"""


class CardClickResponse(BaseModel):
    status: str
    r"""The outcome of the request"""
