"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class ActionType(str, Enum):
    r"""The type of action triggers, either \"action\", or \"cta\"."""

    ACTION = "action"
    CTA = "cta"


class CardClickRequestTypedDict(TypedDict):
    action_id: str
    r"""Human-readable identifier for the card action."""
    action_type: ActionType
    r"""The type of action triggers, either \"action\", or \"cta\"."""


class CardClickRequest(BaseModel):
    action_id: str
    r"""Human-readable identifier for the card action."""

    action_type: ActionType
    r"""The type of action triggers, either \"action\", or \"cta\"."""
