"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from syllable_sdk.types import BaseModel
from typing import List, TYPE_CHECKING
from typing_extensions import TypedDict

if TYPE_CHECKING:
    from .conditionalvalue import ConditionalValue, ConditionalValueTypedDict


class CaseExpressionTypedDict(TypedDict):
    r"""Conditional branch expression.

    Note: CaseExpression is currently reserved and not yet executed at runtime.
    """

    case: List["ConditionalValueTypedDict"]
    r"""Ordered conditional branches (reserved for future runtime support)."""


class CaseExpression(BaseModel):
    r"""Conditional branch expression.

    Note: CaseExpression is currently reserved and not yet executed at runtime.
    """

    case: List["ConditionalValue"]
    r"""Ordered conditional branches (reserved for future runtime support)."""
