"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from syllable_sdk.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class CelExpressionTypedDict(TypedDict):
    r"""See https://github.com/google/cel-spec/blob/master/doc/langdef.md"""

    expression: str
    r"""The expression to evaluate."""
    type: Literal["cel"]
    r"""Google Common Expression Language."""


class CelExpression(BaseModel):
    r"""See https://github.com/google/cel-spec/blob/master/doc/langdef.md"""

    expression: str
    r"""The expression to evaluate."""

    TYPE: Annotated[
        Annotated[Optional[Literal["cel"]], AfterValidator(validate_const("cel"))],
        pydantic.Field(alias="type"),
    ] = "cel"
    r"""Google Common Expression Language."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CelExpression.model_rebuild()
except NameError:
    pass
