"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .a2pmessagingpathcheckrequest import (
    A2pMessagingPathCheckRequest,
    A2pMessagingPathCheckRequestTypedDict,
)
from syllable_sdk.types import BaseModel
from syllable_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ChannelsTwilioNumbersA2pComplianceCheckRequestTypedDict(TypedDict):
    channel_id: int
    a2p_messaging_path_check_request: A2pMessagingPathCheckRequestTypedDict


class ChannelsTwilioNumbersA2pComplianceCheckRequest(BaseModel):
    channel_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    a2p_messaging_path_check_request: Annotated[
        A2pMessagingPathCheckRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
