"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .targetmodes import TargetModes
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ChannelTargetUpdateRequestTypedDict(TypedDict):
    r"""Request model to update a channel target."""

    agent_id: int
    r"""The internal ID of the agent associated with the channel target"""
    channel_id: int
    r"""The internal ID of the channel associated with the channel target"""
    target: str
    r"""The name of the channel target. Must correspond to an organization-level target (available targets can be fetched from `/channels/available-targets`)."""
    target_mode: TargetModes
    r"""Available modes (communication methods) for channel targets."""
    id: int
    r"""The internal ID of the channel target"""
    fallback_target: NotRequired[Nullable[str]]
    r"""The fallback for the channel target (currently only supported for \"voice\" mode)"""
    is_test: NotRequired[bool]
    r"""Whether the channel target is intended for testing. If true, any sessions created through this target will be labeled as a test session (i.e., will not be included in dashboard data and can easily be filtered out in the Sessions screen in the SyllableConsole)."""


class ChannelTargetUpdateRequest(BaseModel):
    r"""Request model to update a channel target."""

    agent_id: int
    r"""The internal ID of the agent associated with the channel target"""

    channel_id: int
    r"""The internal ID of the channel associated with the channel target"""

    target: str
    r"""The name of the channel target. Must correspond to an organization-level target (available targets can be fetched from `/channels/available-targets`)."""

    target_mode: TargetModes
    r"""Available modes (communication methods) for channel targets."""

    id: int
    r"""The internal ID of the channel target"""

    fallback_target: OptionalNullable[str] = UNSET
    r"""The fallback for the channel target (currently only supported for \"voice\" mode)"""

    is_test: Optional[bool] = False
    r"""Whether the channel target is intended for testing. If true, any sessions created through this target will be labeled as a test session (i.e., will not be included in dashboard data and can easily be filtered out in the Sessions screen in the SyllableConsole)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fallback_target", "is_test"])
        nullable_fields = set(["fallback_target"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
