"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .emailconfigurations import EmailConfigurations, EmailConfigurationsTypedDict
from .telephonyconfigurations import (
    TelephonyConfigurations,
    TelephonyConfigurationsTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ChannelConfigViewTypedDict(TypedDict):
    telephony: NotRequired[Nullable[TelephonyConfigurationsTypedDict]]
    r"""Telephony configurations to be applied to targets belonging to the channel.       Only applies to voice supported channels."""
    email: NotRequired[Nullable[EmailConfigurationsTypedDict]]
    r"""Email configurations for email channels. Only applies to email channels."""


class ChannelConfigView(BaseModel):
    telephony: OptionalNullable[TelephonyConfigurations] = UNSET
    r"""Telephony configurations to be applied to targets belonging to the channel.       Only applies to voice supported channels."""

    email: OptionalNullable[EmailConfigurations] = UNSET
    r"""Email configurations for email channels. Only applies to email channels."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["telephony", "email"])
        nullable_fields = set(["telephony", "email"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
