"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ContextToolInfoTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    r"""The name of the generated tool."""
    description: NotRequired[Nullable[str]]
    r"""The description of the tool."""


class ContextToolInfo(BaseModel):
    name: OptionalNullable[str] = UNSET
    r"""The name of the generated tool."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the tool."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "description"])
        nullable_fields = set(["name", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
