"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .custommessagerule import CustomMessageRule, CustomMessageRuleTypedDict
from .custommessagetype import CustomMessageType
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CustomMessageResponseTypedDict(TypedDict):
    r"""Response model for custom message operations.
    A custom message is a pre-configured message delivered by an agent (e.g. as a greeting at the
    beginning of a conversation, or as an email template with subject and body). Multiple agents can
    use the same custom message. Greeting-type messages may have rules for time-based variants; email
    templates have a subject and body only. For more information, see [Console docs](https://docs.syllable.ai/Resources/Messages).
    """

    name: str
    r"""The name of the custom message"""
    text: str
    r"""The default message that the agent will deliver if no rules are set or no rules match the current timestamp. For email_template, this is the body."""
    repeat_after_language_change: bool
    r"""If true, if the caller changes language using the language menu in the custom message, the message will be repeated in the new language (not including the language menu)."""
    id: int
    r"""The ID of the custom message"""
    updated_at: datetime
    r"""Timestamp of the most recent update to the custom message"""
    last_updated_by: str
    r"""The email address of the user who most recently updated the custom message"""
    type: NotRequired[CustomMessageType]
    r"""Type of custom message. Greeting is for voice; email_template is for email (subject + body)."""
    preamble: NotRequired[Nullable[str]]
    r"""An optional preamble that will be delivered before the main message, regardless of whether the current time and date match a rule or the system uses the default message. Cannot contain the \"{{ language.mode }}\" tag. In the case of a voice conversation, the user will not be able to interrupt the preamble. Can be used for e.g. legal disclaimers that the user must always see/hear."""
    subject: NotRequired[Nullable[str]]
    r"""Email subject. Required for email_template (in type_config); ignored otherwise."""
    label: NotRequired[Nullable[str]]
    r"""The label of the custom message"""
    rules: NotRequired[List[CustomMessageRuleTypedDict]]
    r"""Rules for time-specific message variants"""
    agent_count: NotRequired[Nullable[int]]
    r"""The number of agents using the custom message"""


class CustomMessageResponse(BaseModel):
    r"""Response model for custom message operations.
    A custom message is a pre-configured message delivered by an agent (e.g. as a greeting at the
    beginning of a conversation, or as an email template with subject and body). Multiple agents can
    use the same custom message. Greeting-type messages may have rules for time-based variants; email
    templates have a subject and body only. For more information, see [Console docs](https://docs.syllable.ai/Resources/Messages).
    """

    name: str
    r"""The name of the custom message"""

    text: str
    r"""The default message that the agent will deliver if no rules are set or no rules match the current timestamp. For email_template, this is the body."""

    repeat_after_language_change: bool
    r"""If true, if the caller changes language using the language menu in the custom message, the message will be repeated in the new language (not including the language menu)."""

    id: int
    r"""The ID of the custom message"""

    updated_at: datetime
    r"""Timestamp of the most recent update to the custom message"""

    last_updated_by: str
    r"""The email address of the user who most recently updated the custom message"""

    type: Optional[CustomMessageType] = None
    r"""Type of custom message. Greeting is for voice; email_template is for email (subject + body)."""

    preamble: OptionalNullable[str] = UNSET
    r"""An optional preamble that will be delivered before the main message, regardless of whether the current time and date match a rule or the system uses the default message. Cannot contain the \"{{ language.mode }}\" tag. In the case of a voice conversation, the user will not be able to interrupt the preamble. Can be used for e.g. legal disclaimers that the user must always see/hear."""

    subject: OptionalNullable[str] = UNSET
    r"""Email subject. Required for email_template (in type_config); ignored otherwise."""

    label: OptionalNullable[str] = UNSET
    r"""The label of the custom message"""

    rules: Optional[List[CustomMessageRule]] = None
    r"""Rules for time-specific message variants"""

    agent_count: OptionalNullable[int] = UNSET
    r"""The number of agents using the custom message"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "preamble", "subject", "label", "rules", "agent_count"]
        )
        nullable_fields = set(["preamble", "subject", "label", "agent_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
