"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CustomMessageType(str, Enum):
    r"""Type of custom message. Greeting is for voice; email_template is for email (subject + body)."""

    GREETING = "greeting"
    EMAIL_TEMPLATE = "email_template"
