"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DaoExperimentVariantWriteTypedDict(TypedDict):
    r"""One variant of an experiment as it is written.

    Variants are always written as a complete set, because a weight only means anything next to the
    other weights, so there is no model for writing one on its own. The fields are checked by
    `ExperimentsDao._validate_variants` and not by the model, so that every rule about a variant
    reads in one place.
    """

    name: str
    r"""The name of the variant, unique within the experiment"""
    weight: int
    r"""The relative weight of the variant, not a percentage. (E.g., if two variants both have a weight of 10, they are equally likely to be selected.)"""
    agent_id: int
    r"""The agent this variant runs"""
    is_control: NotRequired[bool]
    r"""Whether this is the reference variant the others are measured against"""


class DaoExperimentVariantWrite(BaseModel):
    r"""One variant of an experiment as it is written.

    Variants are always written as a complete set, because a weight only means anything next to the
    other weights, so there is no model for writing one on its own. The fields are checked by
    `ExperimentsDao._validate_variants` and not by the model, so that every rule about a variant
    reads in one place.
    """

    name: str
    r"""The name of the variant, unique within the experiment"""

    weight: int
    r"""The relative weight of the variant, not a percentage. (E.g., if two variants both have a weight of 10, they are equally likely to be selected.)"""

    agent_id: int
    r"""The agent this variant runs"""

    is_control: Optional[bool] = False
    r"""Whether this is the reference variant the others are measured against"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["is_control"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
