"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .targetmodes import TargetModes
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class DaoExperimentTargetSummaryTypedDict(TypedDict):
    r"""The channel target an experiment splits, resolved for display.

    Enough to name the target on the experiment card without a second read: the Console shows the
    target itself and the channel it belongs to, and links to neither by ID.
    """

    id: int
    r"""The internal ID of the channel target"""
    target: str
    r"""The target itself, such as a phone number"""
    target_mode: TargetModes
    r"""Available modes (communication methods) for channel targets."""
    channel_id: int
    r"""The channel the target belongs to"""
    channel_name: str
    r"""The name of that channel"""


class DaoExperimentTargetSummary(BaseModel):
    r"""The channel target an experiment splits, resolved for display.

    Enough to name the target on the experiment card without a second read: the Console shows the
    target itself and the channel it belongs to, and links to neither by ID.
    """

    id: int
    r"""The internal ID of the channel target"""

    target: str
    r"""The target itself, such as a phone number"""

    target_mode: TargetModes
    r"""Available modes (communication methods) for channel targets."""

    channel_id: int
    r"""The channel the target belongs to"""

    channel_name: str
    r"""The name of that channel"""
