"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class DaoExperimentVariantDetailTypedDict(TypedDict):
    r"""A variant, with the name of the agent it runs resolved for display."""

    id: int
    r"""The internal ID of the variant"""
    name: str
    r"""The name of the variant, which is the grouping key in reports"""
    weight: int
    r"""The percentage of the channel target's traffic this variant answers. The weights of an experiment's variants must add up to 100. (E.g., two variants with a weight of 50 each split the traffic evenly.)"""
    is_control: bool
    r"""Whether this is the reference variant the others are measured against"""
    agent_id: int
    r"""The agent this variant runs"""
    agent_name: str
    r"""The name of that agent"""


class DaoExperimentVariantDetail(BaseModel):
    r"""A variant, with the name of the agent it runs resolved for display."""

    id: int
    r"""The internal ID of the variant"""

    name: str
    r"""The name of the variant, which is the grouping key in reports"""

    weight: int
    r"""The percentage of the channel target's traffic this variant answers. The weights of an experiment's variants must add up to 100. (E.g., two variants with a weight of 50 each split the traffic evenly.)"""

    is_control: bool
    r"""Whether this is the reference variant the others are measured against"""

    agent_id: int
    r"""The agent this variant runs"""

    agent_name: str
    r"""The name of that agent"""
