"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class DaoUtmTypedDict(TypedDict):
    utm_source: NotRequired[Nullable[str]]
    utm_medium: NotRequired[Nullable[str]]
    utm_campaign: NotRequired[Nullable[str]]
    utm_term: NotRequired[Nullable[str]]
    utm_content: NotRequired[Nullable[str]]


class DaoUtm(BaseModel):
    utm_source: OptionalNullable[str] = UNSET

    utm_medium: OptionalNullable[str] = UNSET

    utm_campaign: OptionalNullable[str] = UNSET

    utm_term: OptionalNullable[str] = UNSET

    utm_content: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content"]
        )
        nullable_fields = set(
            ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
