"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from typing import Any
from typing_extensions import TypedDict


class DialogToolCallTypedDict(TypedDict):
    tool_call_id: str
    r"""Tool call ID"""
    tool_name: str
    r"""Tool name"""
    tool_arguments: Any
    r"""Tool arguments"""
    tool_result: Nullable[Any]
    r"""Tool result data (only included if tool has propagate_tool_result=true)"""
    timestamp: datetime
    r"""Tool call timestamp"""


class DialogToolCall(BaseModel):
    tool_call_id: str
    r"""Tool call ID"""

    tool_name: str
    r"""Tool name"""

    tool_arguments: Any
    r"""Tool arguments"""

    tool_result: Nullable[Any]
    r"""Tool result data (only included if tool has propagate_tool_result=true)"""

    timestamp: datetime
    r"""Tool call timestamp"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
