"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DictionaryMetadataTypedDict(TypedDict):
    r"""Audit metadata associated with a dictionary."""

    entries: int
    hash: str
    source: NotRequired[str]


class DictionaryMetadata(BaseModel):
    r"""Audit metadata associated with a dictionary."""

    entries: int

    hash: str

    source: Optional[str] = ""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
