"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict, List
from typing_extensions import NotRequired, TypedDict


class DirectoryExtensionNumberTypedDict(TypedDict):
    number: str
    r"""Phone number"""
    rules: NotRequired[Nullable[List[Dict[str, str]]]]
    r"""Directory extension number rules. To include a language rule, use key \"language\" with a language code value."""


class DirectoryExtensionNumber(BaseModel):
    number: str
    r"""Phone number"""

    rules: OptionalNullable[List[Dict[str, str]]] = UNSET
    r"""Directory extension number rules. To include a language rule, use key \"language\" with a language code value."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rules"])
        nullable_fields = set(["rules"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
