"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .directoryextensionnumber import (
    DirectoryExtensionNumber,
    DirectoryExtensionNumberTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class DirectoryExtensionTypedDict(TypedDict):
    name: str
    r"""Directory extension name"""
    numbers: NotRequired[Nullable[List[DirectoryExtensionNumberTypedDict]]]
    r"""Directory extension numbers."""


class DirectoryExtension(BaseModel):
    name: str
    r"""Directory extension name"""

    numbers: OptionalNullable[List[DirectoryExtensionNumber]] = UNSET
    r"""Directory extension numbers."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["numbers"])
        nullable_fields = set(["numbers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
