"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .directoryresponseformat import DirectoryResponseFormat
from .orderbydirection import OrderByDirection
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from syllable_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DirectoryMemberHistoryRequestTypedDict(TypedDict):
    member_id: int
    page: NotRequired[int]
    r"""Page number (0-based)"""
    limit: NotRequired[int]
    r"""Items per page"""
    order_by_direction: NotRequired[OrderByDirection]
    r"""Sort by oldest first (asc) or newest first (desc). Version 1 is always the oldest."""
    response_format: NotRequired[DirectoryResponseFormat]
    r"""Directory response format: normalized (default) strips @hours and formats times; raw returns stored @hours values."""


class DirectoryMemberHistoryRequest(BaseModel):
    member_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Page number (0-based)"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 25
    r"""Items per page"""

    order_by_direction: Annotated[
        Optional[OrderByDirection],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort by oldest first (asc) or newest first (desc). Version 1 is always the oldest."""

    response_format: Annotated[
        Optional[DirectoryResponseFormat],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Directory response format: normalized (default) strips @hours and formats times; raw returns stored @hours values."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page", "limit", "order_by_direction", "response_format"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
