"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displayvaluesource import DisplayValueSource, DisplayValueSourceTypedDict
from enum import Enum
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ValueTypedDict = TypeAliasType(
    "ValueTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


Value = TypeAliasType("Value", Union[DisplayValueSource, str, int, float, bool])


class Kind(str, Enum):
    DATE = "date"
    TIME = "time"
    DATETIME = "datetime"


class Style(str, Enum):
    SHORT = "short"
    MEDIUM = "medium"
    LONG = "long"
    FULL = "full"


class DisplayDateMappingTypedDict(TypedDict):
    r"""A date value resolved from one result item before localization."""

    value: ValueTypedDict
    skeleton: NotRequired[Nullable[str]]
    kind: NotRequired[Nullable[Kind]]
    style: NotRequired[Nullable[Style]]


class DisplayDateMapping(BaseModel):
    r"""A date value resolved from one result item before localization."""

    value: Value

    skeleton: OptionalNullable[str] = UNSET

    kind: OptionalNullable[Kind] = UNSET

    style: OptionalNullable[Style] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["skeleton", "kind", "style"])
        nullable_fields = set(["skeleton", "kind", "style"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
