"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displayvaluesource import DisplayValueSource, DisplayValueSourceTypedDict
from enum import Enum
import pydantic
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class DisplayActionMappingType(str, Enum):
    TEXT = "text"
    LINK = "link"
    BUTTON = "button"
    MESSAGE = "message"


DisplayActionMappingTextTypedDict = TypeAliasType(
    "DisplayActionMappingTextTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayActionMappingText = TypeAliasType(
    "DisplayActionMappingText", Union[DisplayValueSource, str, int, float, bool]
)


class DisplayActionMappingIcon(str, Enum):
    PHONE = "phone"
    EMAIL = "email"
    CHAT = "chat"
    CALENDAR = "calendar"
    ARROW = "arrow"


DisplayActionMappingLinkTypedDict = TypeAliasType(
    "DisplayActionMappingLinkTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayActionMappingLink = TypeAliasType(
    "DisplayActionMappingLink", Union[DisplayValueSource, str, int, float, bool]
)


DisplayActionMappingActionidTypedDict = TypeAliasType(
    "DisplayActionMappingActionidTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayActionMappingActionid = TypeAliasType(
    "DisplayActionMappingActionid", Union[DisplayValueSource, str, int, float, bool]
)


DisplayActionMappingMessageTypedDict = TypeAliasType(
    "DisplayActionMappingMessageTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayActionMappingMessage = TypeAliasType(
    "DisplayActionMappingMessage", Union[DisplayValueSource, str, int, float, bool]
)


class DisplayActionMappingTypedDict(TypedDict):
    type: DisplayActionMappingType
    text: NotRequired[DisplayActionMappingTextTypedDict]
    icon: NotRequired[DisplayActionMappingIcon]
    link: NotRequired[DisplayActionMappingLinkTypedDict]
    action_id: NotRequired[Nullable[DisplayActionMappingActionidTypedDict]]
    message: NotRequired[Nullable[DisplayActionMappingMessageTypedDict]]


class DisplayActionMapping(BaseModel):
    type: DisplayActionMappingType

    text: Optional[DisplayActionMappingText] = None

    icon: Optional[DisplayActionMappingIcon] = DisplayActionMappingIcon.ARROW

    link: Optional[DisplayActionMappingLink] = None

    action_id: Annotated[
        OptionalNullable[DisplayActionMappingActionid], pydantic.Field(alias="actionId")
    ] = UNSET

    message: OptionalNullable[DisplayActionMappingMessage] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["text", "icon", "link", "actionId", "message"])
        nullable_fields = set(["actionId", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    DisplayActionMapping.model_rebuild()
except NameError:
    pass
