"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displayactionmapping import DisplayActionMapping, DisplayActionMappingTypedDict
from .displayctamapping import DisplayCtaMapping, DisplayCtaMappingTypedDict
from .displayvaluesource import DisplayValueSource, DisplayValueSourceTypedDict
import pydantic
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


MediaImageurlTypedDict = TypeAliasType(
    "MediaImageurlTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


MediaImageurl = TypeAliasType(
    "MediaImageurl", Union[DisplayValueSource, str, int, float, bool]
)


MediaOriginalimagewidthTypedDict = TypeAliasType(
    "MediaOriginalimagewidthTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


MediaOriginalimagewidth = TypeAliasType(
    "MediaOriginalimagewidth", Union[DisplayValueSource, str, int, float, bool]
)


MediaOriginalimageheightTypedDict = TypeAliasType(
    "MediaOriginalimageheightTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


MediaOriginalimageheight = TypeAliasType(
    "MediaOriginalimageheight", Union[DisplayValueSource, str, int, float, bool]
)


MediaMaxheightTypedDict = TypeAliasType(
    "MediaMaxheightTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


MediaMaxheight = TypeAliasType(
    "MediaMaxheight", Union[DisplayValueSource, str, int, float, bool]
)


ContentHeaderTypedDict = TypeAliasType(
    "ContentHeaderTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


ContentHeader = TypeAliasType(
    "ContentHeader", Union[DisplayValueSource, str, int, float, bool]
)


ContentSubheaderTypedDict = TypeAliasType(
    "ContentSubheaderTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


ContentSubheader = TypeAliasType(
    "ContentSubheader", Union[DisplayValueSource, str, int, float, bool]
)


ContentDescriptionTypedDict = TypeAliasType(
    "ContentDescriptionTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


ContentDescription = TypeAliasType(
    "ContentDescription", Union[DisplayValueSource, str, int, float, bool]
)


ContentAvatarimageurlTypedDict = TypeAliasType(
    "ContentAvatarimageurlTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


ContentAvatarimageurl = TypeAliasType(
    "ContentAvatarimageurl", Union[DisplayValueSource, str, int, float, bool]
)


ContentContentalwaysleftTypedDict = TypeAliasType(
    "ContentContentalwaysleftTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


ContentContentalwaysleft = TypeAliasType(
    "ContentContentalwaysleft", Union[DisplayValueSource, str, int, float, bool]
)


class DisplayCardMappingTypedDict(TypedDict):
    r"""Supported mappings from one result item to the existing card shape."""

    media_image_url: NotRequired[Nullable[MediaImageurlTypedDict]]
    media_original_image_width: NotRequired[Nullable[MediaOriginalimagewidthTypedDict]]
    media_original_image_height: NotRequired[
        Nullable[MediaOriginalimageheightTypedDict]
    ]
    media_max_height: NotRequired[Nullable[MediaMaxheightTypedDict]]
    content_header: NotRequired[Nullable[ContentHeaderTypedDict]]
    content_subheader: NotRequired[Nullable[ContentSubheaderTypedDict]]
    content_description: NotRequired[Nullable[ContentDescriptionTypedDict]]
    content_avatar_image_url: NotRequired[Nullable[ContentAvatarimageurlTypedDict]]
    content_content_always_left: NotRequired[
        Nullable[ContentContentalwaysleftTypedDict]
    ]
    actions: NotRequired[List[DisplayActionMappingTypedDict]]
    cta: NotRequired[Nullable[DisplayCtaMappingTypedDict]]


class DisplayCardMapping(BaseModel):
    r"""Supported mappings from one result item to the existing card shape."""

    media_image_url: Annotated[
        OptionalNullable[MediaImageurl], pydantic.Field(alias="media.imageUrl")
    ] = UNSET

    media_original_image_width: Annotated[
        OptionalNullable[MediaOriginalimagewidth],
        pydantic.Field(alias="media.originalImageWidth"),
    ] = UNSET

    media_original_image_height: Annotated[
        OptionalNullable[MediaOriginalimageheight],
        pydantic.Field(alias="media.originalImageHeight"),
    ] = UNSET

    media_max_height: Annotated[
        OptionalNullable[MediaMaxheight], pydantic.Field(alias="media.maxHeight")
    ] = UNSET

    content_header: Annotated[
        OptionalNullable[ContentHeader], pydantic.Field(alias="content.header")
    ] = UNSET

    content_subheader: Annotated[
        OptionalNullable[ContentSubheader], pydantic.Field(alias="content.subheader")
    ] = UNSET

    content_description: Annotated[
        OptionalNullable[ContentDescription],
        pydantic.Field(alias="content.description"),
    ] = UNSET

    content_avatar_image_url: Annotated[
        OptionalNullable[ContentAvatarimageurl],
        pydantic.Field(alias="content.avatarImageUrl"),
    ] = UNSET

    content_content_always_left: Annotated[
        OptionalNullable[ContentContentalwaysleft],
        pydantic.Field(alias="content.contentAlwaysLeft"),
    ] = UNSET

    actions: Optional[List[DisplayActionMapping]] = None

    cta: OptionalNullable[DisplayCtaMapping] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "media.imageUrl",
                "media.originalImageWidth",
                "media.originalImageHeight",
                "media.maxHeight",
                "content.header",
                "content.subheader",
                "content.description",
                "content.avatarImageUrl",
                "content.contentAlwaysLeft",
                "actions",
                "cta",
            ]
        )
        nullable_fields = set(
            [
                "media.imageUrl",
                "media.originalImageWidth",
                "media.originalImageHeight",
                "media.maxHeight",
                "content.header",
                "content.subheader",
                "content.description",
                "content.avatarImageUrl",
                "content.contentAlwaysLeft",
                "cta",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    DisplayCardMapping.model_rebuild()
except NameError:
    pass
