"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displayvaluesource import DisplayValueSource, DisplayValueSourceTypedDict
from enum import Enum
import pydantic
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


DisplayCtaMappingTextTypedDict = TypeAliasType(
    "DisplayCtaMappingTextTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayCtaMappingText = TypeAliasType(
    "DisplayCtaMappingText", Union[DisplayValueSource, str, int, float, bool]
)


class DisplayCtaMappingIcon(str, Enum):
    PHONE = "phone"
    EMAIL = "email"
    CHAT = "chat"
    CALENDAR = "calendar"
    ARROW = "arrow"


DisplayCtaMappingLinkTypedDict = TypeAliasType(
    "DisplayCtaMappingLinkTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayCtaMappingLink = TypeAliasType(
    "DisplayCtaMappingLink", Union[DisplayValueSource, str, int, float, bool]
)


DisplayCtaMappingActionidTypedDict = TypeAliasType(
    "DisplayCtaMappingActionidTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayCtaMappingActionid = TypeAliasType(
    "DisplayCtaMappingActionid", Union[DisplayValueSource, str, int, float, bool]
)


DisplayCtaMappingMessageTypedDict = TypeAliasType(
    "DisplayCtaMappingMessageTypedDict",
    Union[DisplayValueSourceTypedDict, str, int, float, bool],
)


DisplayCtaMappingMessage = TypeAliasType(
    "DisplayCtaMappingMessage", Union[DisplayValueSource, str, int, float, bool]
)


class DisplayCtaMappingTypedDict(TypedDict):
    text: NotRequired[DisplayCtaMappingTextTypedDict]
    icon: NotRequired[DisplayCtaMappingIcon]
    link: NotRequired[DisplayCtaMappingLinkTypedDict]
    action_id: NotRequired[Nullable[DisplayCtaMappingActionidTypedDict]]
    message: NotRequired[Nullable[DisplayCtaMappingMessageTypedDict]]


class DisplayCtaMapping(BaseModel):
    text: Optional[DisplayCtaMappingText] = None

    icon: Optional[DisplayCtaMappingIcon] = DisplayCtaMappingIcon.ARROW

    link: Optional[DisplayCtaMappingLink] = None

    action_id: Annotated[
        OptionalNullable[DisplayCtaMappingActionid], pydantic.Field(alias="actionId")
    ] = UNSET

    message: OptionalNullable[DisplayCtaMappingMessage] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["text", "icon", "link", "actionId", "message"])
        nullable_fields = set(["actionId", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    DisplayCtaMapping.model_rebuild()
except NameError:
    pass
