"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displaydatemapping import DisplayDateMapping, DisplayDateMappingTypedDict
from .displayvaluesource import DisplayValueSource, DisplayValueSourceTypedDict
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ParamsTypedDict = TypeAliasType(
    "ParamsTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


Params = TypeAliasType("Params", Union[DisplayValueSource, str, int, float, bool])


ProseTypedDict = TypeAliasType(
    "ProseTypedDict", Union[DisplayValueSourceTypedDict, str, int, float, bool]
)


Prose = TypeAliasType("Prose", Union[DisplayValueSource, str, int, float, bool])


class DisplayPhraseMappingTypedDict(TypedDict):
    r"""A producer-owned localized phrase with per-item dynamic values."""

    template: str
    params: NotRequired[Dict[str, ParamsTypedDict]]
    prose: NotRequired[Dict[str, ProseTypedDict]]
    dates: NotRequired[Dict[str, DisplayDateMappingTypedDict]]


class DisplayPhraseMapping(BaseModel):
    r"""A producer-owned localized phrase with per-item dynamic values."""

    template: str

    params: Optional[Dict[str, Params]] = None

    prose: Optional[Dict[str, Prose]] = None

    dates: Optional[Dict[str, DisplayDateMapping]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["params", "prose", "dates"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
