"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Any
from typing_extensions import NotRequired, TypedDict


class DisplayValueSourceTypedDict(TypedDict):
    r"""Select or interpolate a value from one item in a tool result."""

    path: NotRequired[Nullable[str]]
    template: NotRequired[Nullable[str]]
    default: NotRequired[Nullable[Any]]


class DisplayValueSource(BaseModel):
    r"""Select or interpolate a value from one item in a tool result."""

    path: OptionalNullable[str] = UNSET

    template: OptionalNullable[str] = UNSET

    default: OptionalNullable[Any] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["path", "template", "default"])
        nullable_fields = set(["path", "template", "default"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
