"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class EmailConfigurationsTypedDict(TypedDict):
    r"""Email channel configurations."""

    sending_domain: str
    r"""The domain to use for sending emails. Must be authenticated in SendGrid."""


class EmailConfigurations(BaseModel):
    r"""Email channel configurations."""

    sending_domain: str
    r"""The domain to use for sending emails. Must be authenticated in SendGrid."""
