"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ExperimentProperties(str, Enum):
    ID = "id"
    NAME = "name"
    NAME_EXACT = "name_exact"
    DESCRIPTION = "description"
    STATUS = "status"
    TARGET_ID = "target_id"
    AGENT_ID = "agent_id"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    STARTED_AT = "started_at"
    STOPPED_AT = "stopped_at"
