"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .daoexperimenttargetsummary import (
    DaoExperimentTargetSummary,
    DaoExperimentTargetSummaryTypedDict,
)
from .daoexperimentvariantdetail import (
    DaoExperimentVariantDetail,
    DaoExperimentVariantDetailTypedDict,
)
from .experimentstatus import ExperimentStatus
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class ExperimentResponseTypedDict(TypedDict):
    r"""Response model for experiment operations.

    An experiment splits the traffic of one channel target between two or more agents, so that the
    agents can be compared on the same population. One variant is the control the others are
    measured against. Each variant is a weighted pointer to the agent that variant runs; the weights
    are relative and not percentages.
    """

    id: int
    r"""The internal ID of the experiment"""
    name: str
    r"""The name of the experiment"""
    target_id: Nullable[int]
    r"""The channel target being split, or null if that target has since been deleted. A running experiment always has one."""
    variants: List[DaoExperimentVariantDetailTypedDict]
    r"""The variants of the experiment, in a stable order"""
    status: ExperimentStatus
    r"""Status of an experiment.

    The column is a varchar and not a database enum, so a new value here does not need a migration.
    """
    created_at: datetime
    r"""When the experiment was created"""
    updated_at: datetime
    r"""When the experiment was last written"""
    last_updated_by: str
    r"""Who last wrote it"""
    description: NotRequired[Nullable[str]]
    r"""The hypothesis under test"""
    started_at: NotRequired[Nullable[datetime]]
    r"""When the experiment started"""
    stopped_at: NotRequired[Nullable[datetime]]
    r"""When the experiment stopped"""
    target: NotRequired[Nullable[DaoExperimentTargetSummaryTypedDict]]
    r"""The channel target being split, resolved for display. Null when the target has since been deleted, and when the read did not load it."""


class ExperimentResponse(BaseModel):
    r"""Response model for experiment operations.

    An experiment splits the traffic of one channel target between two or more agents, so that the
    agents can be compared on the same population. One variant is the control the others are
    measured against. Each variant is a weighted pointer to the agent that variant runs; the weights
    are relative and not percentages.
    """

    id: int
    r"""The internal ID of the experiment"""

    name: str
    r"""The name of the experiment"""

    target_id: Nullable[int]
    r"""The channel target being split, or null if that target has since been deleted. A running experiment always has one."""

    variants: List[DaoExperimentVariantDetail]
    r"""The variants of the experiment, in a stable order"""

    status: ExperimentStatus
    r"""Status of an experiment.

    The column is a varchar and not a database enum, so a new value here does not need a migration.
    """

    created_at: datetime
    r"""When the experiment was created"""

    updated_at: datetime
    r"""When the experiment was last written"""

    last_updated_by: str
    r"""Who last wrote it"""

    description: OptionalNullable[str] = UNSET
    r"""The hypothesis under test"""

    started_at: OptionalNullable[datetime] = UNSET
    r"""When the experiment started"""

    stopped_at: OptionalNullable[datetime] = UNSET
    r"""When the experiment stopped"""

    target: OptionalNullable[DaoExperimentTargetSummary] = UNSET
    r"""The channel target being split, resolved for display. Null when the target has since been deleted, and when the read did not load it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "started_at", "stopped_at", "target"])
        nullable_fields = set(
            ["target_id", "description", "started_at", "stopped_at", "target"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
