"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .daoexperimentvariantwrite import (
    DaoExperimentVariantWrite,
    DaoExperimentVariantWriteTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ExperimentUpdateRequestTypedDict(TypedDict):
    r"""Request model to update an experiment."""

    name: str
    r"""The name of the experiment"""
    description: NotRequired[Nullable[str]]
    r"""The hypothesis under test"""
    variants: NotRequired[List[DaoExperimentVariantWriteTypedDict]]
    r"""The variants of the experiment, as a complete set. Two or more, each on a different agent, exactly one of them the control."""


class ExperimentUpdateRequest(BaseModel):
    r"""Request model to update an experiment."""

    name: str
    r"""The name of the experiment"""

    description: OptionalNullable[str] = UNSET
    r"""The hypothesis under test"""

    variants: Optional[List[DaoExperimentVariantWrite]] = None
    r"""The variants of the experiment, as a complete set. Two or more, each on a different agent, exactly one of them the control."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "variants"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
