"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .experimentresponse import ExperimentResponse, ExperimentResponseTypedDict
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ExperimentStartResponseTypedDict(TypedDict):
    r"""A started experiment."""

    experiment: ExperimentResponseTypedDict
    r"""Response model for experiment operations.

    An experiment splits the traffic of one channel target between two or more agents, so that the
    agents can be compared on the same population. One variant is the control the others are
    measured against. Each variant is a weighted pointer to the agent that variant runs; the weights
    are relative and not percentages.
    """
    warnings: NotRequired[List[str]]
    r"""Things that weaken the result without invalidating it, such as a variant whose agent does not pin a prompt version, so that the prompt can be edited while the experiment runs"""


class ExperimentStartResponse(BaseModel):
    r"""A started experiment."""

    experiment: ExperimentResponse
    r"""Response model for experiment operations.

    An experiment splits the traffic of one channel target between two or more agents, so that the
    agents can be compared on the same population. One variant is the control the others are
    measured against. Each variant is a weighted pointer to the agent that variant runs; the weights
    are relative and not percentages.
    """

    warnings: Optional[List[str]] = None
    r"""Things that weaken the result without invalidating it, such as a variant whose agent does not pin a prompt version, so that the prompt can be edited while the experiment runs"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["warnings"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
