"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FilterOp(str, Enum):
    r"""Comparison operator for a single target-filter rule."""

    IN = "in"
    NOT_IN = "not_in"
    EQ = "eq"
    NEQ = "neq"
    EXISTS = "exists"
    NOT_EXISTS = "not_exists"
