"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class Holiday(str, Enum):
    r"""All available named holidays"""

    CHRISTMAS_DAY = "christmas-day"
    CHRISTMAS_DAY_OBSERVED = "christmas-day-observed"
    CHRISTMAS_EVE = "christmas-eve"
    INDEPENDENCE_DAY = "independence-day"
    INDEPENDENCE_DAY_OBSERVED = "independence-day-observed"
    INDIGENOUS_PEOPLES_DAY = "indigenous-peoples-day"
    COLUMBUS_DAY = "columbus-day"
    JUNETEENTH = "juneteenth"
    JUNETEENTH_OBSERVED = "juneteenth-observed"
    LABOR_DAY = "labor-day"
    MEMORIAL_DAY = "memorial-day"
    MLK_DAY = "mlk-day"
    NEW_YEARS_DAY = "new-years-day"
    NEW_YEARS_DAY_OBSERVED = "new-years-day-observed"
    NEW_YEARS_EVE = "new-years-eve"
    PRESIDENTS_DAY = "presidents-day"
    THANKSGIVING_DAY = "thanksgiving-day"
    THANKSGIVING_DAY_AFTER = "thanksgiving-day-after"
    THANKSGIVING_DAY_BEFORE = "thanksgiving-day-before"
    VETERANS_DAY = "veterans-day"
    VETERANS_DAY_OBSERVED = "veterans-day-observed"
    GOOD_FRIDAY = "good-friday"
