"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class InsightWorkflowExecutionOutputTypedDict(TypedDict):
    r"""Response model for a row in the insight_workflow_execution table."""

    id: int
    r"""Unique ID of the workflow execution row"""
    workflow_id: int
    r"""ID of the workflow this execution belongs to"""
    status: str
    r"""Status of the workflow execution"""
    priority: int
    r"""Priority of the workflow execution"""
    retry_count: int
    r"""Number of times this execution has been retried"""
    created_at: datetime
    r"""Timestamp at which the execution row was created (i.e. when the work was queued)"""
    session_id: NotRequired[Nullable[int]]
    r"""Session ID processed by this execution, if applicable"""
    upload_file_id: NotRequired[Nullable[int]]
    r"""Upload file ID processed by this execution, if applicable"""
    error_message: NotRequired[Nullable[str]]
    r"""Error message from the last processing attempt, if any"""
    started_at: NotRequired[Nullable[datetime]]
    r"""Timestamp at which the most recent processing attempt started"""
    event_type: NotRequired[Nullable[str]]
    r"""Event type that triggered the execution, if applicable"""


class InsightWorkflowExecutionOutput(BaseModel):
    r"""Response model for a row in the insight_workflow_execution table."""

    id: int
    r"""Unique ID of the workflow execution row"""

    workflow_id: int
    r"""ID of the workflow this execution belongs to"""

    status: str
    r"""Status of the workflow execution"""

    priority: int
    r"""Priority of the workflow execution"""

    retry_count: int
    r"""Number of times this execution has been retried"""

    created_at: datetime
    r"""Timestamp at which the execution row was created (i.e. when the work was queued)"""

    session_id: OptionalNullable[int] = UNSET
    r"""Session ID processed by this execution, if applicable"""

    upload_file_id: OptionalNullable[int] = UNSET
    r"""Upload file ID processed by this execution, if applicable"""

    error_message: OptionalNullable[str] = UNSET
    r"""Error message from the last processing attempt, if any"""

    started_at: OptionalNullable[datetime] = UNSET
    r"""Timestamp at which the most recent processing attempt started"""

    event_type: OptionalNullable[str] = UNSET
    r"""Event type that triggered the execution, if applicable"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "session_id",
                "upload_file_id",
                "error_message",
                "started_at",
                "event_type",
            ]
        )
        nullable_fields = set(
            [
                "session_id",
                "upload_file_id",
                "error_message",
                "started_at",
                "event_type",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
