"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InsightWorkflowExecutionSummaryTypedDict(TypedDict):
    r"""How many of a workflow's executions are in each status, optionally within a
    created_at date range. Counts cover all matching rows, not just one page.
    """

    pending: NotRequired[int]
    r"""Rows in PENDING status"""
    processing: NotRequired[int]
    r"""Rows in PROCESSING status"""
    completed: NotRequired[int]
    r"""Rows in COMPLETED status"""
    failed: NotRequired[int]
    r"""Rows in FAILED status"""
    total: NotRequired[int]
    r"""Total rows across all statuses"""


class InsightWorkflowExecutionSummary(BaseModel):
    r"""How many of a workflow's executions are in each status, optionally within a
    created_at date range. Counts cover all matching rows, not just one page.
    """

    pending: Optional[int] = 0
    r"""Rows in PENDING status"""

    processing: Optional[int] = 0
    r"""Rows in PROCESSING status"""

    completed: Optional[int] = 0
    r"""Rows in COMPLETED status"""

    failed: Optional[int] = 0
    r"""Rows in FAILED status"""

    total: Optional[int] = 0
    r"""Total rows across all statuses"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pending", "processing", "completed", "failed", "total"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
