"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class InsightsWorkflowQueueSessionTypedDict(TypedDict):
    r"""Session identifier for workflow queue."""

    workflow_name: str
    r"""Unique name for workflow"""
    session_id_list: NotRequired[Nullable[List[int]]]
    r"""List of session identifiers"""
    file_id_list: NotRequired[Nullable[List[int]]]
    r"""List of file IDs to be processed. This is only applicable for upload folders"""


class InsightsWorkflowQueueSession(BaseModel):
    r"""Session identifier for workflow queue."""

    workflow_name: str
    r"""Unique name for workflow"""

    session_id_list: OptionalNullable[List[int]] = UNSET
    r"""List of session identifiers"""

    file_id_list: OptionalNullable[List[int]] = UNSET
    r"""List of file IDs to be processed. This is only applicable for upload folders"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["session_id_list", "file_id_list"])
        nullable_fields = set(["session_id_list", "file_id_list"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
