"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .insighttooldefinition import InsightToolDefinition, InsightToolDefinitionTypedDict
from .validationissue import ValidationIssue, ValidationIssueTypedDict
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Any, List, Optional
from typing_extensions import NotRequired, TypedDict


class InsightToolResponseTypedDict(TypedDict):
    r"""Response model for insight tool saves, carrying any non-blocking findings."""

    name: str
    r"""Human readable name of insight tool"""
    description: str
    r"""Text description of insight tool configuration"""
    version: int
    r"""Version of insight tool"""
    tool_arguments: Any
    r"""Arguments for calling the insight tool"""
    insight_tool_definition_id: int
    r"""Unique ID for insight tool definition used by this tool configuration"""
    id: int
    r"""Unique ID for insight tool"""
    last_updated_by: str
    r"""Email of user who last updated insight tool configuration"""
    insight_tool_definition: NotRequired[Nullable[InsightToolDefinitionTypedDict]]
    r"""Insight Tool Definition"""
    created_at: NotRequired[datetime]
    r"""Timestamp of at which insight tool configuration was created"""
    updated_at: NotRequired[datetime]
    r"""Timestamp at which insight tool configuration was last updated"""
    validation_issues: NotRequired[Nullable[List[ValidationIssueTypedDict]]]
    r"""Non-blocking findings for the saved insight tool (e.g. a deprecated model warning). Warnings and infos are informational; errors block the save."""


class InsightToolResponse(BaseModel):
    r"""Response model for insight tool saves, carrying any non-blocking findings."""

    name: str
    r"""Human readable name of insight tool"""

    description: str
    r"""Text description of insight tool configuration"""

    version: int
    r"""Version of insight tool"""

    tool_arguments: Any
    r"""Arguments for calling the insight tool"""

    insight_tool_definition_id: int
    r"""Unique ID for insight tool definition used by this tool configuration"""

    id: int
    r"""Unique ID for insight tool"""

    last_updated_by: str
    r"""Email of user who last updated insight tool configuration"""

    insight_tool_definition: OptionalNullable[InsightToolDefinition] = UNSET
    r"""Insight Tool Definition"""

    created_at: Optional[datetime] = None
    r"""Timestamp of at which insight tool configuration was created"""

    updated_at: Optional[datetime] = None
    r"""Timestamp at which insight tool configuration was last updated"""

    validation_issues: OptionalNullable[List[ValidationIssue]] = UNSET
    r"""Non-blocking findings for the saved insight tool (e.g. a deprecated model warning). Warnings and infos are informational; errors block the save."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["insight_tool_definition", "created_at", "updated_at", "validation_issues"]
        )
        nullable_fields = set(["insight_tool_definition", "validation_issues"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
