"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class InsightsFolderInputTypedDict(TypedDict):
    r"""Request model to create/update an insight upload folder."""

    name: str
    r"""Human-readable name of insight folder"""
    label: NotRequired[Nullable[str]]
    r"""optional label assigned to insight folder"""
    description: NotRequired[Nullable[str]]
    r"""Text description of insight upload folder"""


class InsightsFolderInput(BaseModel):
    r"""Request model to create/update an insight upload folder."""

    name: str
    r"""Human-readable name of insight folder"""

    label: OptionalNullable[str] = UNSET
    r"""optional label assigned to insight folder"""

    description: OptionalNullable[str] = UNSET
    r"""Text description of insight upload folder"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["label", "description"])
        nullable_fields = set(["label", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
