"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from syllable_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, NotRequired, TypedDict


class InsightsWorkflowExecutionsSummaryRequestTypedDict(TypedDict):
    workflow_id: int
    start_datetime: NotRequired[Nullable[str]]
    r"""ISO 8601 start datetime (inclusive) for created_at filtering"""
    end_datetime: NotRequired[Nullable[str]]
    r"""ISO 8601 end datetime (exclusive) for created_at filtering"""


class InsightsWorkflowExecutionsSummaryRequest(BaseModel):
    workflow_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    start_datetime: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""ISO 8601 start datetime (inclusive) for created_at filtering"""

    end_datetime: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""ISO 8601 end datetime (exclusive) for created_at filtering"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start_datetime", "end_datetime"])
        nullable_fields = set(["start_datetime", "end_datetime"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
