"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class InsightWorkflowExecutionProperties(str, Enum):
    ID = "id"
    STATUS = "status"
    CREATED_AT = "created_at"
    STARTED_AT = "started_at"
    PRIORITY = "priority"
    SESSION_ID = "session_id"
    UPLOAD_FILE_ID = "upload_file_id"
    EVENT_TYPE = "event_type"
