"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .latencyentry import LatencyEntry, LatencyEntryTypedDict
from .summaryentry import SummaryEntry, SummaryEntryTypedDict
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class InspectLatencyResponseTypedDict(TypedDict):
    r"""This is a report of the time spent in each operation during this session. It contains a timeline,
    which lists the operations in the order they were executed, and a summary, which aggregates the
    operations by category and sub-category.
    """

    session_id: str
    timeline: List[LatencyEntryTypedDict]
    summary: NotRequired[List[SummaryEntryTypedDict]]


class InspectLatencyResponse(BaseModel):
    r"""This is a report of the time spent in each operation during this session. It contains a timeline,
    which lists the operations in the order they were executed, and a summary, which aggregates the
    operations by category and sub-category.
    """

    session_id: str

    timeline: List[LatencyEntry]

    summary: Optional[List[SummaryEntry]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["summary"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
