"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolfunction import ToolFunction, ToolFunctionTypedDict
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from syllable_sdk.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class InternalToolTypedDict(TypedDict):
    r"""A tool definition to be used by the OpenAI API."""

    function: ToolFunctionTypedDict
    r"""A function available to an agent.

    See:
    - https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling
    """
    type: Literal["function"]
    r"""Always `function`."""


class InternalTool(BaseModel):
    r"""A tool definition to be used by the OpenAI API."""

    function: ToolFunction
    r"""A function available to an agent.

    See:
    - https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling
    """

    TYPE: Annotated[
        Annotated[
            Optional[Literal["function"]], AfterValidator(validate_const("function"))
        ],
        pydantic.Field(alias="type"),
    ] = "function"
    r"""Always `function`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    InternalTool.model_rebuild()
except NameError:
    pass
