"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class JMESPathExpressionType(str, Enum):
    r"""JMESPath expression."""

    JP = "jp"
    JMESPATH = "jmespath"


class JMESPathExpressionTypedDict(TypedDict):
    r"""See https://jmespath.org/specification.html#grammar"""

    expression: str
    r"""The expression to evaluate."""
    type: NotRequired[JMESPathExpressionType]
    r"""JMESPath expression."""


class JMESPathExpression(BaseModel):
    r"""See https://jmespath.org/specification.html#grammar"""

    expression: str
    r"""The expression to evaluate."""

    type: Optional[JMESPathExpressionType] = JMESPathExpressionType.JP
    r"""JMESPath expression."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
