"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .localizedbridgephrases import (
    LocalizedBridgePhrases,
    LocalizedBridgePhrasesTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessagesTypedDict(
    TypedDict
):
    r"""Bridge phrase messages for a single scope (default or one tool)."""

    messages: NotRequired[List[str]]
    r"""Ordered bridge phrases for this scope."""
    localized: NotRequired[Dict[str, LocalizedBridgePhrasesTypedDict]]
    r"""Per-language overrides keyed by BCP-47 tag (e.g. \"es-US\")."""


class LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages(BaseModel):
    r"""Bridge phrase messages for a single scope (default or one tool)."""

    messages: Optional[List[str]] = None
    r"""Ordered bridge phrases for this scope."""

    localized: Optional[Dict[str, LocalizedBridgePhrases]] = None
    r"""Per-language overrides keyed by BCP-47 tag (e.g. \"es-US\")."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["messages", "localized"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
