"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LifecycleStatus(str, Enum):
    r"""Effective deprecation state of a model, resolved against a reference date."""

    ACTIVE = "active"
    DEPRECATED = "deprecated"
    RETIRED = "retired"
