"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LineTypeBucket(str, Enum):
    r"""Friendly line-type buckets a campaign can be restricted to dial.

    These map to raw Twilio Lookup v2 line types via
    ``lib.twilio.line_type_lookup.LINE_TYPE_BUCKETS``.
    """

    MOBILE = "mobile"
    LANDLINE = "landline"
    VOIP = "voip"
