"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .voicegroupresponse import VoiceGroupResponse, VoiceGroupResponseTypedDict
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class ListResponseVoiceGroupResponseTypedDict(TypedDict):
    items: List[VoiceGroupResponseTypedDict]
    r"""List of items returned from the query"""
    page: int
    r"""The page number of the results (0-based)"""
    page_size: int
    r"""The number of items returned per page"""
    total_pages: NotRequired[Nullable[int]]
    r"""The total number of pages of results given the indicated page size"""
    total_count: NotRequired[Nullable[int]]
    r"""The total number of items returned from the query"""


class ListResponseVoiceGroupResponse(BaseModel):
    items: List[VoiceGroupResponse]
    r"""List of items returned from the query"""

    page: int
    r"""The page number of the results (0-based)"""

    page_size: int
    r"""The number of items returned per page"""

    total_pages: OptionalNullable[int] = UNSET
    r"""The total number of pages of results given the indicated page size"""

    total_count: OptionalNullable[int] = UNSET
    r"""The total number of items returned from the query"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total_pages", "total_count"])
        nullable_fields = set(["total_pages", "total_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
