"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LocalizedBridgePhrasesTypedDict(TypedDict):
    r"""Per-language bridge phrase overrides (no further nesting)."""

    messages: NotRequired[List[str]]
    r"""Bridge phrases for this language."""


class LocalizedBridgePhrases(BaseModel):
    r"""Per-language bridge phrase overrides (no further nesting)."""

    messages: Optional[List[str]] = None
    r"""Bridge phrases for this language."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["messages"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
