"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationsipiprangeupdate import (
    OrganizationSipIPRangeUpdate,
    OrganizationSipIPRangeUpdateTypedDict,
)
from syllable_sdk.types import BaseModel
from syllable_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class OrganizationSipIPRangesUpdateRequestTypedDict(TypedDict):
    sip_ip_range_id: int
    organization_sip_ip_range_update: OrganizationSipIPRangeUpdateTypedDict


class OrganizationSipIPRangesUpdateRequest(BaseModel):
    sip_ip_range_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    organization_sip_ip_range_update: Annotated[
        OrganizationSipIPRangeUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
