"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationsipiprangetype import OrganizationSipIPRangeType
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class OrganizationSipIPRangeTypedDict(TypedDict):
    r"""SIP IP range object."""

    type: OrganizationSipIPRangeType
    r"""The type of SIP IP range. Signaling IP ranges are used for SIP signaling traffic (e.g. SIP INVITE,
    SIP REFER, SIP OPTIONS, etc.), while media IP ranges are used for SIP media traffic
    (audio and video).
    """
    ip_range: str
    r"""The SIP IP range in CIDR notation"""
    id: int
    r"""The organization SIP IP range ID"""
    organization_id: int
    r"""The Organization ID"""
    verified: bool
    r"""Whether Syllable has verified this SIP IP range.Verification implies that the Syllable team has updated the firewall rules on the SBCs, confirmed traffic is correctly established from/to the customer network and calls to Syllable agents are working."""
    created_at: NotRequired[Nullable[datetime]]
    r"""The timestamp when the range was created"""
    updated_at: NotRequired[Nullable[datetime]]
    r"""The timestamp when the range was last updated"""
    deleted_at: NotRequired[Nullable[datetime]]
    r"""The timestamp when the IP was deleted"""


class OrganizationSipIPRange(BaseModel):
    r"""SIP IP range object."""

    type: OrganizationSipIPRangeType
    r"""The type of SIP IP range. Signaling IP ranges are used for SIP signaling traffic (e.g. SIP INVITE,
    SIP REFER, SIP OPTIONS, etc.), while media IP ranges are used for SIP media traffic
    (audio and video).
    """

    ip_range: str
    r"""The SIP IP range in CIDR notation"""

    id: int
    r"""The organization SIP IP range ID"""

    organization_id: int
    r"""The Organization ID"""

    verified: bool
    r"""Whether Syllable has verified this SIP IP range.Verification implies that the Syllable team has updated the firewall rules on the SBCs, confirmed traffic is correctly established from/to the customer network and calls to Syllable agents are working."""

    created_at: OptionalNullable[datetime] = UNSET
    r"""The timestamp when the range was created"""

    updated_at: OptionalNullable[datetime] = UNSET
    r"""The timestamp when the range was last updated"""

    deleted_at: OptionalNullable[datetime] = UNSET
    r"""The timestamp when the IP was deleted"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["created_at", "updated_at", "deleted_at"])
        nullable_fields = set(["created_at", "updated_at", "deleted_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
