"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationsipiprangetype import OrganizationSipIPRangeType
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class OrganizationSipIPRangeCreateTypedDict(TypedDict):
    r"""The request body for creating a new SIP IP range."""

    type: OrganizationSipIPRangeType
    r"""The type of SIP IP range. Signaling IP ranges are used for SIP signaling traffic (e.g. SIP INVITE,
    SIP REFER, SIP OPTIONS, etc.), while media IP ranges are used for SIP media traffic
    (audio and video).
    """
    ip_range: str
    r"""The SIP IP range in CIDR notation"""


class OrganizationSipIPRangeCreate(BaseModel):
    r"""The request body for creating a new SIP IP range."""

    type: OrganizationSipIPRangeType
    r"""The type of SIP IP range. Signaling IP ranges are used for SIP signaling traffic (e.g. SIP INVITE,
    SIP REFER, SIP OPTIONS, etc.), while media IP ranges are used for SIP media traffic
    (audio and video).
    """

    ip_range: str
    r"""The SIP IP range in CIDR notation"""
