"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class OrganizationResponseTypedDict(TypedDict):
    display_name: str
    r"""The human-readable display name of the organization."""
    id: int
    r"""The internal ID of the organization."""
    slug: str
    r"""The slug of the organization used for URLs in the Console UI"""
    last_updated: datetime
    r"""The timestamp of the most recent update to the organization"""
    description: NotRequired[Nullable[str]]
    r"""Description of the organization."""
    domains: NotRequired[Nullable[str]]
    r"""Comma-delimited list of domains that users at the organization may have in their email addresses."""
    saml_provider_id: NotRequired[Nullable[str]]
    r"""SAML provider ID for user authentication"""
    last_updated_comments: NotRequired[Nullable[str]]
    r"""Comments for the most recent edit to the organization."""
    last_updated_by: NotRequired[Nullable[str]]
    r"""The email of the user who most recently updated the organization"""
    logo_url: NotRequired[Nullable[str]]
    r"""CDN URL. The org will always have a logo, but this value will be null on a response to an update where no logo was provided on the request"""


class OrganizationResponse(BaseModel):
    display_name: str
    r"""The human-readable display name of the organization."""

    id: int
    r"""The internal ID of the organization."""

    slug: str
    r"""The slug of the organization used for URLs in the Console UI"""

    last_updated: datetime
    r"""The timestamp of the most recent update to the organization"""

    description: OptionalNullable[str] = UNSET
    r"""Description of the organization."""

    domains: OptionalNullable[str] = UNSET
    r"""Comma-delimited list of domains that users at the organization may have in their email addresses."""

    saml_provider_id: OptionalNullable[str] = UNSET
    r"""SAML provider ID for user authentication"""

    last_updated_comments: OptionalNullable[str] = UNSET
    r"""Comments for the most recent edit to the organization."""

    last_updated_by: OptionalNullable[str] = UNSET
    r"""The email of the user who most recently updated the organization"""

    logo_url: OptionalNullable[str] = UNSET
    r"""CDN URL. The org will always have a logo, but this value will be null on a response to an update where no logo was provided on the request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "domains",
                "saml_provider_id",
                "last_updated_comments",
                "last_updated_by",
                "logo_url",
            ]
        )
        nullable_fields = set(
            [
                "description",
                "domains",
                "saml_provider_id",
                "last_updated_comments",
                "last_updated_by",
                "logo_url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
