"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class OrganizationSipIPRangeType(str, Enum):
    r"""The type of SIP IP range. Signaling IP ranges are used for SIP signaling traffic (e.g. SIP INVITE,
    SIP REFER, SIP OPTIONS, etc.), while media IP ranges are used for SIP media traffic
    (audio and video).
    """

    SIGNALING = "signaling"
    MEDIA = "media"
