"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .organizationsipiprangetype import OrganizationSipIPRangeType
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class OrganizationSipIPRangeUpdateTypedDict(TypedDict):
    r"""The request body for updating a SIP IP range."""

    type: NotRequired[Nullable[OrganizationSipIPRangeType]]
    r"""The SIP IP range type"""
    ip_range: NotRequired[Nullable[str]]
    r"""The SIP IP range in CIDR notation"""


class OrganizationSipIPRangeUpdate(BaseModel):
    r"""The request body for updating a SIP IP range."""

    type: OptionalNullable[OrganizationSipIPRangeType] = UNSET
    r"""The SIP IP range type"""

    ip_range: OptionalNullable[str] = UNSET
    r"""The SIP IP range in CIDR notation"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "ip_range"])
        nullable_fields = set(["type", "ip_range"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
