"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channelmanagerstatus import ChannelManagerStatus
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict, List
from typing_extensions import NotRequired, TypedDict


class OutboundCampaignWebhookInputTypedDict(TypedDict):
    trigger_statuses: List[ChannelManagerStatus]
    r"""Condition expression evaluated when the trigger fires"""
    url: str
    r"""HTTPS URL to which to send the webhook payload"""
    request_method: str
    r"""HTTP method for the outbound request (POST, PUT, or PATCH)"""
    id: NotRequired[Nullable[int]]
    r"""Unique ID for webhook, if updating an existing webhook"""
    auth_values: NotRequired[Nullable[Dict[str, Nullable[str]]]]
    r"""Optional dict of auth values. Currently, only the key \"hmac_secret\" is allowed; value must be standard Base64 (RFC 4648) decoding to 32–512 bytes of key material. On update, leave a value for a given key null and the stored value for that key is kept. (If a key is omitted entirely, any existing value for that key is removed.)"""


class OutboundCampaignWebhookInput(BaseModel):
    trigger_statuses: List[ChannelManagerStatus]
    r"""Condition expression evaluated when the trigger fires"""

    url: str
    r"""HTTPS URL to which to send the webhook payload"""

    request_method: str
    r"""HTTP method for the outbound request (POST, PUT, or PATCH)"""

    id: OptionalNullable[int] = UNSET
    r"""Unique ID for webhook, if updating an existing webhook"""

    auth_values: OptionalNullable[Dict[str, Nullable[str]]] = UNSET
    r"""Optional dict of auth values. Currently, only the key \"hmac_secret\" is allowed; value must be standard Base64 (RFC 4648) decoding to 32–512 bytes of key material. On update, leave a value for a given key null and the stored value for that key is kept. (If a key is omitted entirely, any existing value for that key is removed.)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "auth_values"])
        nullable_fields = set(["id", "auth_values"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
