"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channelmanagerstatus import ChannelManagerStatus
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class OutboundCampaignWebhookResponseTypedDict(TypedDict):
    trigger_statuses: List[ChannelManagerStatus]
    r"""Condition expression evaluated when the trigger fires"""
    url: str
    r"""HTTPS URL to which to send the webhook payload"""
    request_method: str
    r"""HTTP method for the outbound request (POST, PUT, or PATCH)"""
    id: int
    r"""Unique ID for webhook"""
    auth_value_keys: NotRequired[Nullable[List[str]]]
    r"""Auth value keys (values omitted for security); only hmac_secret is currently supported"""


class OutboundCampaignWebhookResponse(BaseModel):
    trigger_statuses: List[ChannelManagerStatus]
    r"""Condition expression evaluated when the trigger fires"""

    url: str
    r"""HTTPS URL to which to send the webhook payload"""

    request_method: str
    r"""HTTP method for the outbound request (POST, PUT, or PATCH)"""

    id: int
    r"""Unique ID for webhook"""

    auth_value_keys: OptionalNullable[List[str]] = UNSET
    r"""Auth value keys (values omitted for security); only hmac_secret is currently supported"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_value_keys"])
        nullable_fields = set(["auth_value_keys"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
