"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scheduleoverride import ScheduleOverride, ScheduleOverrideTypedDict
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class OutreachOverrideRulesTypedDict(TypedDict):
    r"""Weekday- and date-specific outreach rules for a campaign.

    The most specific rule wins: a rule for the calendar date, then a rule for the weekday, then the
    campaign defaults (``daily_start_time`` / ``daily_end_time`` / ``max_daily_calls`` /
    ``active_days``). Resolution is per field, so a date rule that only moves the end time still uses
    the weekday cap. All days, dates and times are in the time zone of the agent the campaign dials
    from -- see ``lib.outbound.schedule``.
    """

    days: NotRequired[Dict[str, ScheduleOverrideTypedDict]]
    r"""Rules by weekday. Full names (monday) and short names (mon) are both accepted; they are stored as short names. Days that are absent use the campaign defaults."""
    dates: NotRequired[Dict[str, ScheduleOverrideTypedDict]]
    r"""Rules by calendar date, keyed YYYY-MM-DD. A date rule wins over the weekday rule for that date."""


class OutreachOverrideRules(BaseModel):
    r"""Weekday- and date-specific outreach rules for a campaign.

    The most specific rule wins: a rule for the calendar date, then a rule for the weekday, then the
    campaign defaults (``daily_start_time`` / ``daily_end_time`` / ``max_daily_calls`` /
    ``active_days``). Resolution is per field, so a date rule that only moves the end time still uses
    the weekday cap. All days, dates and times are in the time zone of the agent the campaign dials
    from -- see ``lib.outbound.schedule``.
    """

    days: Optional[Dict[str, ScheduleOverride]] = None
    r"""Rules by weekday. Full names (monday) and short names (mon) are both accepted; they are stored as short names. Days that are absent use the campaign defaults."""

    dates: Optional[Dict[str, ScheduleOverride]] = None
    r"""Rules by calendar date, keyed YYYY-MM-DD. A date rule wins over the weekday rule for that date."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["days", "dates"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
