"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cardclickrequest import CardClickRequest, CardClickRequestTypedDict
from syllable_sdk.types import BaseModel
from syllable_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PostCardClickEventRequestTypedDict(TypedDict):
    test_id: str
    card_click_request: CardClickRequestTypedDict


class PostCardClickEventRequest(BaseModel):
    test_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    card_click_request: Annotated[
        CardClickRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
