"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict
from typing_extensions import NotRequired, TypedDict


class RequestStatusBreakdownTypedDict(TypedDict):
    r"""Per-request_status breakdown with total count and optional channel_manager_status counts."""

    total_count: int
    r"""Total number of requests with this request_status"""
    counts: NotRequired[Nullable[Dict[str, int]]]
    r"""Counts by channel_manager_status within this request_status; omitted if none"""


class RequestStatusBreakdown(BaseModel):
    r"""Per-request_status breakdown with total count and optional channel_manager_status counts."""

    total_count: int
    r"""Total number of requests with this request_status"""

    counts: OptionalNullable[Dict[str, int]] = UNSET
    r"""Counts by channel_manager_status within this request_status; omitted if none"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["counts"])
        nullable_fields = set(["counts"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
