"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .displaycardmapping import DisplayCardMapping, DisplayCardMappingTypedDict
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from syllable_sdk.utils import validate_const
from typing import Literal, Optional
from typing_extensions import Annotated, TypedDict


class ResponseDisplayConfigTypedDict(TypedDict):
    r"""Declarative presentation metadata stored with a tool definition."""

    items_path: str
    mapping: DisplayCardMappingTypedDict
    r"""Supported mappings from one result item to the existing card shape."""
    version: Literal[1]
    type: Literal["card-list"]


class ResponseDisplayConfig(BaseModel):
    r"""Declarative presentation metadata stored with a tool definition."""

    items_path: str

    mapping: DisplayCardMapping
    r"""Supported mappings from one result item to the existing card shape."""

    VERSION: Annotated[
        Annotated[Optional[Literal[1]], AfterValidator(validate_const(1))],
        pydantic.Field(alias="version"),
    ] = 1

    TYPE: Annotated[
        Annotated[Literal["card-list"], AfterValidator(validate_const("card-list"))],
        pydantic.Field(alias="type"),
    ] = "card-list"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ResponseDisplayConfig.model_rebuild()
except NameError:
    pass
