"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class RoleCreateRequestTypedDict(TypedDict):
    r"""Request model to create a role."""

    name: str
    r"""The name of the role."""
    permissions: List[str]
    r"""The permissions associated with the role. Available permissions can be found by calling `GET /permissions`."""
    description: NotRequired[Nullable[str]]
    r"""The description of the role."""


class RoleCreateRequest(BaseModel):
    r"""Request model to create a role."""

    name: str
    r"""The name of the role."""

    permissions: List[str]
    r"""The permissions associated with the role. Available permissions can be found by calling `GET /permissions`."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the role."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
