"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ScheduleOverrideTypedDict(TypedDict):
    r"""Outreach window and/or daily cap for one weekday or one calendar date.

    Every field may be omitted, and an omitted field inherits the campaign default: an override that
    only sets ``max_daily_calls`` keeps the campaign window, and one that only sets the times keeps
    the campaign cap. ``max_daily_calls: 0`` is not inheritance -- it is an explicit \"no outreach on
    this day\", which is the shape the Outbound Scheduler daily_limit config already uses. It closes
    the day for retries as well as for first attempts, the same way ``active: false`` does; a
    non-zero maximum bounds first attempts only and lets retries run on.
    """

    active: NotRequired[Nullable[bool]]
    r"""Whether the campaign does outreach on this day. Omitted inherits: a weekday rule inherits from active_days, a date rule inherits from the weekday rule. Set it to false to close one date, for example a holiday, without a change to active_days."""
    daily_start_time: NotRequired[Nullable[str]]
    r"""Start time on this day. Omitted keeps the campaign start time."""
    daily_end_time: NotRequired[Nullable[str]]
    r"""End time on this day. Omitted keeps the campaign end time."""
    max_daily_calls: NotRequired[Nullable[int]]
    r"""Maximum number of unique reference IDs that get outreach on this day. Omitted keeps the campaign maximum. Retries do not count towards it and keep dialing once it is reached. 0 is different: it closes the day for all outreach, retries included."""


class ScheduleOverride(BaseModel):
    r"""Outreach window and/or daily cap for one weekday or one calendar date.

    Every field may be omitted, and an omitted field inherits the campaign default: an override that
    only sets ``max_daily_calls`` keeps the campaign window, and one that only sets the times keeps
    the campaign cap. ``max_daily_calls: 0`` is not inheritance -- it is an explicit \"no outreach on
    this day\", which is the shape the Outbound Scheduler daily_limit config already uses. It closes
    the day for retries as well as for first attempts, the same way ``active: false`` does; a
    non-zero maximum bounds first attempts only and lets retries run on.
    """

    active: OptionalNullable[bool] = UNSET
    r"""Whether the campaign does outreach on this day. Omitted inherits: a weekday rule inherits from active_days, a date rule inherits from the weekday rule. Set it to false to close one date, for example a holiday, without a change to active_days."""

    daily_start_time: OptionalNullable[str] = UNSET
    r"""Start time on this day. Omitted keeps the campaign start time."""

    daily_end_time: OptionalNullable[str] = UNSET
    r"""End time on this day. Omitted keeps the campaign end time."""

    max_daily_calls: OptionalNullable[int] = UNSET
    r"""Maximum number of unique reference IDs that get outreach on this day. Omitted keeps the campaign maximum. Retries do not count towards it and keep dialing once it is reached. 0 is different: it closes the day for all outreach, retries included."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["active", "daily_start_time", "daily_end_time", "max_daily_calls"]
        )
        nullable_fields = set(
            ["active", "daily_start_time", "daily_end_time", "max_daily_calls"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
