"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class SessionRecordingResponseTypedDict(TypedDict):
    r"""Recording URLs for a given session."""

    session_id: NotRequired[Nullable[str]]
    r"""The internal ID of the session"""
    recordings: NotRequired[Nullable[List[str]]]
    r"""List of recording URLs"""


class SessionRecordingResponse(BaseModel):
    r"""Recording URLs for a given session."""

    session_id: OptionalNullable[str] = UNSET
    r"""The internal ID of the session"""

    recordings: OptionalNullable[List[str]] = UNSET
    r"""List of recording URLs"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["session_id", "recordings"])
        nullable_fields = set(["session_id", "recordings"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
