"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class SessionSummaryResponseTypedDict(TypedDict):
    r"""AI summary information for a given session."""

    summary: NotRequired[Nullable[str]]
    r"""The AI summary of the session"""
    rating: NotRequired[Nullable[str]]
    r"""The AI rating of the session"""


class SessionSummaryResponse(BaseModel):
    r"""AI summary information for a given session."""

    summary: OptionalNullable[str] = UNSET
    r"""The AI summary of the session"""

    rating: OptionalNullable[str] = UNSET
    r"""The AI rating of the session"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["summary", "rating"])
        nullable_fields = set(["summary", "rating"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
