"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .timelineevent import TimelineEvent, TimelineEventTypedDict
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class SessionTimelineResponseTypedDict(TypedDict):
    r"""Consolidated, time-ordered timeline of a session's events."""

    session_id: str
    r"""Internal ID of the session"""
    events: List[TimelineEventTypedDict]
    r"""All events, ordered by timestamp ascending"""
    session_start: NotRequired[Nullable[datetime]]
    r"""Timestamp of the first event; the zero point for all offsets"""


class SessionTimelineResponse(BaseModel):
    r"""Consolidated, time-ordered timeline of a session's events."""

    session_id: str
    r"""Internal ID of the session"""

    events: List[TimelineEvent]
    r"""All events, ordered by timestamp ascending"""

    session_start: OptionalNullable[datetime] = UNSET
    r"""Timestamp of the first event; the zero point for all offsets"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["session_start"])
        nullable_fields = set(["session_start"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
