"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sipendpoint import SipEndpoint, SipEndpointTypedDict
from .siptransfermode import SipTransferMode
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class SipConfigurationTypedDict(TypedDict):
    r"""SIP routing configuration for transferring a call to a destination.

    This is internal telephony/routing configuration used to direct a transfer to specific
    SIP endpoints.
    """

    sip_transfer_mode: NotRequired[Nullable[SipTransferMode]]
    r"""How to perform the SIP transfer, INVITE or REFER."""
    sip_endpoints: NotRequired[Nullable[List[SipEndpointTypedDict]]]
    r"""List of SIP endpoints to attempt for the transfer."""


class SipConfiguration(BaseModel):
    r"""SIP routing configuration for transferring a call to a destination.

    This is internal telephony/routing configuration used to direct a transfer to specific
    SIP endpoints.
    """

    sip_transfer_mode: OptionalNullable[SipTransferMode] = UNSET
    r"""How to perform the SIP transfer, INVITE or REFER."""

    sip_endpoints: OptionalNullable[List[SipEndpoint]] = UNSET
    r"""List of SIP endpoints to attempt for the transfer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sip_transfer_mode", "sip_endpoints"])
        nullable_fields = set(["sip_transfer_mode", "sip_endpoints"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
