"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .siptransport import SipTransport
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class SipEndpointTypedDict(TypedDict):
    r"""A single SIP endpoint to attempt for a transfer."""

    host: str
    r"""SIP endpoint host (IP address or hostname)."""
    port: NotRequired[Nullable[str]]
    r"""SIP endpoint port."""
    transport: NotRequired[Nullable[SipTransport]]
    r"""SIP transport protocol, e.g. `tcp`, `tls` or `udp`."""


class SipEndpoint(BaseModel):
    r"""A single SIP endpoint to attempt for a transfer."""

    host: str
    r"""SIP endpoint host (IP address or hostname)."""

    port: OptionalNullable[str] = UNSET
    r"""SIP endpoint port."""

    transport: OptionalNullable[SipTransport] = UNSET
    r"""SIP transport protocol, e.g. `tcp`, `tls` or `udp`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["port", "transport"])
        nullable_fields = set(["port", "transport"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
