"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SipTransferMode(str, Enum):
    r"""How a call should be transferred to a SIP endpoint."""

    REFER = "refer"
    INVITE = "invite"
