"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SipTransport(str, Enum):
    r"""The transport protocol to use for the SIP endpoint."""

    TLS = "tls"
    TCP = "tcp"
    UDP = "udp"
