"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class StepToolsTypedDict(TypedDict):
    r"""Configuration for tools available in a step."""

    call: NotRequired[Nullable[bool]]
    r"""Whether to force immediate tool call without user interaction."""
    allow: NotRequired[Nullable[List[str]]]
    r"""List of allowed tool names for this step."""
    allow_go_to_step: NotRequired[Nullable[bool]]
    r"""Whether to expose the go_to_step escape hatch to the LLM. Defaults to disabled."""


class StepTools(BaseModel):
    r"""Configuration for tools available in a step."""

    call: OptionalNullable[bool] = UNSET
    r"""Whether to force immediate tool call without user interaction."""

    allow: OptionalNullable[List[str]] = UNSET
    r"""List of allowed tool names for this step."""

    allow_go_to_step: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="allowGoToStep")
    ] = UNSET
    r"""Whether to expose the go_to_step escape hatch to the LLM. Defaults to disabled."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["call", "allow", "allowGoToStep"])
        nullable_fields = set(["call", "allow", "allowGoToStep"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    StepTools.model_rebuild()
except NameError:
    pass
