"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lifecyclestatus import LifecycleStatus
from datetime import date
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SupportedSttProviderTypedDict(TypedDict):
    r"""An STT provider offered to agents, with its resolved deprecation lifecycle."""

    provider: str
    r"""Speech-to-text provider value, as stored on the agent."""
    display_name: str
    r"""Human-readable name of the provider."""
    deprecated: NotRequired[bool]
    r"""Whether the provider is in the deprecation warning window."""
    sunset_date: NotRequired[Nullable[date]]
    r"""Date the provider becomes retired and can no longer be saved or selected."""
    removed: NotRequired[bool]
    r"""Whether the provider is force-retired regardless of sunset_date."""
    fallback: NotRequired[Nullable[str]]
    r"""Provider substituted at runtime for critical features once this one is retired."""
    status: NotRequired[Nullable[LifecycleStatus]]
    r"""Effective lifecycle status, resolved server-side against the current date."""


class SupportedSttProvider(BaseModel):
    r"""An STT provider offered to agents, with its resolved deprecation lifecycle."""

    provider: str
    r"""Speech-to-text provider value, as stored on the agent."""

    display_name: str
    r"""Human-readable name of the provider."""

    deprecated: Optional[bool] = False
    r"""Whether the provider is in the deprecation warning window."""

    sunset_date: OptionalNullable[date] = UNSET
    r"""Date the provider becomes retired and can no longer be saved or selected."""

    removed: Optional[bool] = False
    r"""Whether the provider is force-retired regardless of sunset_date."""

    fallback: OptionalNullable[str] = UNSET
    r"""Provider substituted at runtime for critical features once this one is retired."""

    status: OptionalNullable[LifecycleStatus] = UNSET
    r"""Effective lifecycle status, resolved server-side against the current date."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["deprecated", "sunset_date", "removed", "fallback", "status"]
        )
        nullable_fields = set(["sunset_date", "fallback", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
