"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lifecyclestatus import LifecycleStatus
from .promptllmprovider import PromptLlmProvider
from datetime import date
import pydantic
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SupportedLlmTypedDict(TypedDict):
    r"""LLM config option that can be used on a prompt."""

    display_name: str
    r"""Display name of the model. This is used for display purposes in the Console UI."""
    deprecated: bool
    r"""Whether the model is in the deprecation warning window."""
    provider: NotRequired[PromptLlmProvider]
    r"""LLM API provider."""
    model: NotRequired[str]
    r"""Name of the model. Must match the deployment name in Azure AI Studio."""
    version: NotRequired[Nullable[str]]
    r"""Deprecated model version retained for backward compatibility."""
    api_version: NotRequired[Nullable[str]]
    r"""Version of the provider's API."""
    sunset_date: NotRequired[Nullable[date]]
    r"""Date the model becomes retired and can no longer be saved or selected."""
    removed: NotRequired[bool]
    r"""Whether the model is force-retired regardless of sunset_date."""
    fallback: NotRequired[Nullable[str]]
    r"""Model substituted at runtime for critical features once this one is retired."""
    status: NotRequired[Nullable[LifecycleStatus]]
    r"""Effective lifecycle status, resolved server-side against the current date. Populated on API responses; unset in the static catalog."""


class SupportedLlm(BaseModel):
    r"""LLM config option that can be used on a prompt."""

    display_name: str
    r"""Display name of the model. This is used for display purposes in the Console UI."""

    deprecated: bool
    r"""Whether the model is in the deprecation warning window."""

    provider: Optional[PromptLlmProvider] = None
    r"""LLM API provider."""

    model: Optional[str] = "gpt-4o"
    r"""Name of the model. Must match the deployment name in Azure AI Studio."""

    version: Annotated[
        OptionalNullable[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = UNSET
    r"""Deprecated model version retained for backward compatibility."""

    api_version: OptionalNullable[str] = UNSET
    r"""Version of the provider's API."""

    sunset_date: OptionalNullable[date] = UNSET
    r"""Date the model becomes retired and can no longer be saved or selected."""

    removed: Optional[bool] = False
    r"""Whether the model is force-retired regardless of sunset_date."""

    fallback: OptionalNullable[str] = UNSET
    r"""Model substituted at runtime for critical features once this one is retired."""

    status: OptionalNullable[LifecycleStatus] = UNSET
    r"""Effective lifecycle status, resolved server-side against the current date. Populated on API responses; unset in the static catalog."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "provider",
                "model",
                "version",
                "api_version",
                "sunset_date",
                "removed",
                "fallback",
                "status",
            ]
        )
        nullable_fields = set(
            ["version", "api_version", "sunset_date", "fallback", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
