"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .takeoutrequeststatus import TakeoutRequestStatus
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class TakeoutStatusResponseTypedDict(TypedDict):
    job_id: str
    status: TakeoutRequestStatus
    r"""Status of a takeout request."""
    updated_at: datetime
    file_names: NotRequired[Nullable[List[str]]]


class TakeoutStatusResponse(BaseModel):
    job_id: str

    status: TakeoutRequestStatus
    r"""Status of a takeout request."""

    updated_at: datetime

    file_names: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_names"])
        nullable_fields = set(["file_names"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
