"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filterop import FilterOp
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TargetFilterRuleTypedDict(TypedDict):
    r"""A single predicate over one enrichment attribute of an outbound request.

    ``field`` names a key in the request's enrichment payload (e.g. ``line_type``, ``carrier_name``,
    ``mcc``, ``mnc``). Any attribute captured at lookup time can be filtered on with no code change.
    """

    field: str
    r"""Enrichment attribute to match on (a key in the request enrichment payload)."""
    op: FilterOp
    r"""Comparison operator for a single target-filter rule."""
    values: NotRequired[List[str]]
    r"""Values to compare against. Ignored for exists / not_exists."""


class TargetFilterRule(BaseModel):
    r"""A single predicate over one enrichment attribute of an outbound request.

    ``field`` names a key in the request's enrichment payload (e.g. ``line_type``, ``carrier_name``,
    ``mcc``, ``mnc``). Any attribute captured at lookup time can be filtered on with no code change.
    """

    field: str
    r"""Enrichment attribute to match on (a key in the request enrichment payload)."""

    op: FilterOp
    r"""Comparison operator for a single target-filter rule."""

    values: Optional[List[str]] = None
    r"""Values to compare against. Ignored for exists / not_exists."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
