"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .targetfilterrule import TargetFilterRule, TargetFilterRuleTypedDict
from enum import Enum
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class Match(str, Enum):
    r"""How to combine rules: 'all' (AND) or 'any' (OR)."""

    ALL = "all"
    ANY = "any"


class OnUnknown(str, Enum):
    r"""Whether to dial requests whose enrichment is unresolved (no lookup data)."""

    INCLUDE = "include"
    EXCLUDE = "exclude"


class TargetFiltersTypedDict(TypedDict):
    r"""Generic target filter for an outbound campaign: a flat list of rules over request enrichment.

    A request is *dialable* when it matches the ruleset (``match='all'`` -> every rule; ``'any'`` ->
    at least one rule); non-matching requests are skipped. ``on_unknown`` decides the fate of
    requests whose enrichment never resolved (no lookup / lookup failed). An empty ``rules`` list
    means no filter (all numbers dialed), matching the pre-filter behavior.
    """

    match: NotRequired[Match]
    r"""How to combine rules: 'all' (AND) or 'any' (OR)."""
    on_unknown: NotRequired[OnUnknown]
    r"""Whether to dial requests whose enrichment is unresolved (no lookup data)."""
    rules: NotRequired[List[TargetFilterRuleTypedDict]]
    r"""Predicates over request enrichment attributes. Empty means no filter."""


class TargetFilters(BaseModel):
    r"""Generic target filter for an outbound campaign: a flat list of rules over request enrichment.

    A request is *dialable* when it matches the ruleset (``match='all'`` -> every rule; ``'any'`` ->
    at least one rule); non-matching requests are skipped. ``on_unknown`` decides the fate of
    requests whose enrichment never resolved (no lookup / lookup failed). An empty ``rules`` list
    means no filter (all numbers dialed), matching the pre-filter behavior.
    """

    match: Optional[Match] = Match.ALL
    r"""How to combine rules: 'all' (AND) or 'any' (OR)."""

    on_unknown: Optional[OnUnknown] = OnUnknown.INCLUDE
    r"""Whether to dial requests whose enrichment is unresolved (no lookup data)."""

    rules: Optional[List[TargetFilterRule]] = None
    r"""Predicates over request enrichment attributes. Empty means no filter."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["match", "on_unknown", "rules"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
