"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .timelineeventkind import TimelineEventKind
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class TimelineEventTypedDict(TypedDict):
    r"""A single normalized event on the consolidated session timeline."""

    kind: TimelineEventKind
    timestamp: datetime
    r"""Absolute time of the event (for ordering)"""
    offset: str
    r"""Time since session start, formatted MM:SS (or HH:MM:SS)"""
    turn_index: NotRequired[Nullable[int]]
    r"""0-based index of the transcript turn. Transcript events carry their own turn index; tool/latency events carry the index of the nearest preceding turn they bind to. None only for non-transcript events that precede the first transcript turn."""
    source: NotRequired[Nullable[str]]
    r"""\"user\" or \"agent\" (transcript events)"""
    text: NotRequired[Nullable[str]]
    r"""Message content (transcript events)"""
    lang: NotRequired[Nullable[str]]
    r"""Language code (transcript events)"""
    category: NotRequired[Nullable[str]]
    r"""tool | llm | tts | stt | http. A tool call surfaces once, as a `kind=tool` event; its redundant tool-latency measurement is dropped from the timeline."""
    label: NotRequired[Nullable[str]]
    r"""Tool name (tool events) or the latency measurement name (e.g. stt_processing)"""
    metadata: NotRequired[Nullable[List[str]]]
    r"""Provider/model parts of a latency label"""
    duration_ms: NotRequired[Nullable[float]]
    r"""Duration of the event in milliseconds"""
    tool_request: NotRequired[Nullable[str]]
    r"""Tool request payload, JSON-encoded"""
    tool_result: NotRequired[Nullable[str]]
    r"""Tool response payload, JSON-encoded"""
    tool_error: NotRequired[Nullable[str]]
    r"""Tool error payload, JSON-encoded"""


class TimelineEvent(BaseModel):
    r"""A single normalized event on the consolidated session timeline."""

    kind: TimelineEventKind

    timestamp: datetime
    r"""Absolute time of the event (for ordering)"""

    offset: str
    r"""Time since session start, formatted MM:SS (or HH:MM:SS)"""

    turn_index: OptionalNullable[int] = UNSET
    r"""0-based index of the transcript turn. Transcript events carry their own turn index; tool/latency events carry the index of the nearest preceding turn they bind to. None only for non-transcript events that precede the first transcript turn."""

    source: OptionalNullable[str] = UNSET
    r"""\"user\" or \"agent\" (transcript events)"""

    text: OptionalNullable[str] = UNSET
    r"""Message content (transcript events)"""

    lang: OptionalNullable[str] = UNSET
    r"""Language code (transcript events)"""

    category: OptionalNullable[str] = UNSET
    r"""tool | llm | tts | stt | http. A tool call surfaces once, as a `kind=tool` event; its redundant tool-latency measurement is dropped from the timeline."""

    label: OptionalNullable[str] = UNSET
    r"""Tool name (tool events) or the latency measurement name (e.g. stt_processing)"""

    metadata: OptionalNullable[List[str]] = UNSET
    r"""Provider/model parts of a latency label"""

    duration_ms: OptionalNullable[float] = UNSET
    r"""Duration of the event in milliseconds"""

    tool_request: OptionalNullable[str] = UNSET
    r"""Tool request payload, JSON-encoded"""

    tool_result: OptionalNullable[str] = UNSET
    r"""Tool response payload, JSON-encoded"""

    tool_error: OptionalNullable[str] = UNSET
    r"""Tool error payload, JSON-encoded"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "turn_index",
                "source",
                "text",
                "lang",
                "category",
                "label",
                "metadata",
                "duration_ms",
                "tool_request",
                "tool_result",
                "tool_error",
            ]
        )
        nullable_fields = set(
            [
                "turn_index",
                "source",
                "text",
                "lang",
                "category",
                "label",
                "metadata",
                "duration_ms",
                "tool_request",
                "tool_result",
                "tool_error",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
