"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ConfigTypedDict(TypedDict):
    r"""Type-specific JSON configuration (e.g. HTTP endpoint, context, or action wiring)"""


class Config(BaseModel):
    r"""Type-specific JSON configuration (e.g. HTTP endpoint, context, or action wiring)"""


class ToolHistoryResponseDefaultsTypedDict(TypedDict):
    r"""Default parameter values for this tool when invoked"""


class ToolHistoryResponseDefaults(BaseModel):
    r"""Default parameter values for this tool when invoked"""


class ResultTypedDict(TypedDict):
    r"""JSON describing the tool result shape or response schema"""


class Result(BaseModel):
    r"""JSON describing the tool result shape or response schema"""


class DefinitionTypedDict(TypedDict):
    r"""The definition of the tool (same shape as create/update; stored as JSON)"""


class Definition(BaseModel):
    r"""The definition of the tool (same shape as create/update; stored as JSON)"""


class ToolHistoryResponseTypedDict(TypedDict):
    r"""API response for one row in GET /tools/{tool_id}/history."""

    tool_id: int
    r"""ID of the tool"""
    version_number: int
    r"""Monotonic version for this tool (1 = oldest)"""
    created_at: datetime
    r"""When this version took effect."""
    updated_by: str
    r"""User who made the change that produced this row"""
    operation: str
    r"""What produced this row: create, update, or delete"""
    service_id: int
    r"""Internal ID of the service this tool belonged to at this version"""
    name: str
    r"""Tool name at this version"""
    description: str
    r"""Human-readable description of the tool at this version"""
    type: str
    r"""Tool type at this version: 'action', 'endpoint', 'context', or 'log'"""
    comments: NotRequired[Nullable[str]]
    r"""Optional comment stored on the tool for this version"""
    deleted_reason: NotRequired[Nullable[str]]
    r"""When operation is delete, reason copied from the tool at delete time"""
    service_name: NotRequired[Nullable[str]]
    r"""Service display name."""
    config: NotRequired[ConfigTypedDict]
    r"""Type-specific JSON configuration (e.g. HTTP endpoint, context, or action wiring)"""
    defaults: NotRequired[ToolHistoryResponseDefaultsTypedDict]
    r"""Default parameter values for this tool when invoked"""
    result: NotRequired[ResultTypedDict]
    r"""JSON describing the tool result shape or response schema"""
    definition: NotRequired[DefinitionTypedDict]
    r"""The definition of the tool (same shape as create/update; stored as JSON)"""


class ToolHistoryResponse(BaseModel):
    r"""API response for one row in GET /tools/{tool_id}/history."""

    tool_id: int
    r"""ID of the tool"""

    version_number: int
    r"""Monotonic version for this tool (1 = oldest)"""

    created_at: datetime
    r"""When this version took effect."""

    updated_by: str
    r"""User who made the change that produced this row"""

    operation: str
    r"""What produced this row: create, update, or delete"""

    service_id: int
    r"""Internal ID of the service this tool belonged to at this version"""

    name: str
    r"""Tool name at this version"""

    description: str
    r"""Human-readable description of the tool at this version"""

    type: str
    r"""Tool type at this version: 'action', 'endpoint', 'context', or 'log'"""

    comments: OptionalNullable[str] = UNSET
    r"""Optional comment stored on the tool for this version"""

    deleted_reason: OptionalNullable[str] = UNSET
    r"""When operation is delete, reason copied from the tool at delete time"""

    service_name: OptionalNullable[str] = UNSET
    r"""Service display name."""

    config: Optional[Config] = None
    r"""Type-specific JSON configuration (e.g. HTTP endpoint, context, or action wiring)"""

    defaults: Optional[ToolHistoryResponseDefaults] = None
    r"""Default parameter values for this tool when invoked"""

    result: Optional[Result] = None
    r"""JSON describing the tool result shape or response schema"""

    definition: Optional[Definition] = None
    r"""The definition of the tool (same shape as create/update; stored as JSON)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "comments",
                "deleted_reason",
                "service_name",
                "config",
                "defaults",
                "result",
                "definition",
            ]
        )
        nullable_fields = set(["comments", "deleted_reason", "service_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
