"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lib_database_dao_organization_bridge_phrases_dao_bridgephrasemessages import (
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages,
    LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessagesTypedDict,
)
from syllable_sdk.types import BaseModel
from typing_extensions import TypedDict


class ToolBridgePhraseConfigTypedDict(TypedDict):
    r"""Per-tool bridge phrase override entry."""

    tool_name: str
    r"""Name of the tool these phrases override."""
    phrases: LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessagesTypedDict
    r"""Bridge phrase messages for a single scope (default or one tool)."""


class ToolBridgePhraseConfig(BaseModel):
    r"""Per-tool bridge phrase override entry."""

    tool_name: str
    r"""Name of the tool these phrases override."""

    phrases: LibDatabaseDaoOrganizationBridgePhrasesDaoBridgePhraseMessages
    r"""Bridge phrase messages for a single scope (default or one tool)."""
