"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ToolOptionsTypedDict(TypedDict):
    r"""The options for a tool call."""

    propagate_tool_result: NotRequired[bool]
    r"""Whether the tool call result should be propagated to the caller."""


class ToolOptions(BaseModel):
    r"""The options for a tool call."""

    propagate_tool_result: Optional[bool] = False
    r"""Whether the tool call result should be propagated to the caller."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["propagate_tool_result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
