"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolargumentlocation import ToolArgumentLocation
from .toolhttpmethod import ToolHTTPMethod
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ToolHTTPEndpointTypedDict(TypedDict):
    r"""The configuration for an HTTP API call by a tool."""

    url: str
    r"""The endpoint URL of the external service to call."""
    method: ToolHTTPMethod
    r"""The HTTP method to use for a tool HTTP request."""
    argument_location: ToolArgumentLocation
    r"""The location of the argument in a tool HTTP request.
    'body' is used for JSON data in the POST request body.
    'form' is used for form data in the POST request body.
    'path' is used for URL path parameters.
    'query' is used for query parameters in the URL.
    """
    timeout: NotRequired[Nullable[float]]
    r"""Timeout in seconds for the HTTP request. Default 20 seconds when not set."""


class ToolHTTPEndpoint(BaseModel):
    r"""The configuration for an HTTP API call by a tool."""

    url: str
    r"""The endpoint URL of the external service to call."""

    method: ToolHTTPMethod
    r"""The HTTP method to use for a tool HTTP request."""

    argument_location: ToolArgumentLocation
    r"""The location of the argument in a tool HTTP request.
    'body' is used for JSON data in the POST request body.
    'form' is used for form data in the POST request body.
    'path' is used for URL path parameters.
    'query' is used for query parameters in the URL.
    """

    timeout: OptionalNullable[float] = UNSET
    r"""Timeout in seconds for the HTTP request. Default 20 seconds when not set."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["timeout"])
        nullable_fields = set(["timeout"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
