"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from syllable_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET_SENTINEL
from syllable_sdk.utils import validate_const
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ToolParameterTransformConditionTypedDict(TypedDict):
    r"""A condition to be met for a transform to be applied to the value of a tool parameter."""

    key: str
    r"""The name of the parameter to check."""
    value: str
    r"""The value to check against the parameter."""
    operator: Nullable[Literal["eq"]]
    r"""The operator to use for the comparison. Currently only supports \"eq\" """


class ToolParameterTransformCondition(BaseModel):
    r"""A condition to be met for a transform to be applied to the value of a tool parameter."""

    key: str
    r"""The name of the parameter to check."""

    value: str
    r"""The value to check against the parameter."""

    OPERATOR: Annotated[
        Annotated[
            OptionalNullable[Literal["eq"]], AfterValidator(validate_const("eq"))
        ],
        pydantic.Field(alias="operator"),
    ] = "eq"
    r"""The operator to use for the comparison. Currently only supports \"eq\" """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["operator"])
        nullable_fields = set(["operator"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ToolParameterTransformCondition.model_rebuild()
except NameError:
    pass
