"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tooldefinition import ToolDefinition, ToolDefinitionTypedDict
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ToolUpdateRequestTypedDict(TypedDict):
    r"""Request model to update an existing tool."""

    name: str
    r"""The name of the tool"""
    definition: ToolDefinitionTypedDict
    r"""A tool that can be called from an LLM during the conversation. See https://docs.syllable.ai/Resources/Tools."""
    service_id: int
    r"""Internal ID of the service to which the tool belongs"""
    id: int
    r"""The internal ID of the tool"""
    last_updated_comments: NotRequired[Nullable[str]]
    r"""Comments for the most recent edit to the tool."""


class ToolUpdateRequest(BaseModel):
    r"""Request model to update an existing tool."""

    name: str
    r"""The name of the tool"""

    definition: ToolDefinition
    r"""A tool that can be called from an LLM during the conversation. See https://docs.syllable.ai/Resources/Tools."""

    service_id: int
    r"""Internal ID of the service to which the tool belongs"""

    id: int
    r"""The internal ID of the tool"""

    last_updated_comments: OptionalNullable[str] = UNSET
    r"""Comments for the most recent edit to the tool."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["last_updated_comments"])
        nullable_fields = set(["last_updated_comments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
