"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tooldefinition import ToolDefinition, ToolDefinitionTypedDict
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class ToolHistoryResponseTypedDict(TypedDict):
    r"""API response for one row in GET /tools/{tool_id}/history."""

    tool_id: int
    r"""ID of the tool"""
    version_number: int
    r"""Monotonic version for this tool (1 = oldest)"""
    created_at: datetime
    r"""When this version took effect."""
    updated_by: str
    r"""User who made the change that produced this row"""
    operation: str
    r"""What produced this row: create, update, or delete"""
    service_id: int
    r"""Internal ID of the service this tool belonged to at this version"""
    name: str
    r"""Tool name at this version"""
    description: str
    r"""Human-readable description of the tool at this version"""
    type: str
    r"""Tool type at this version: 'action', 'endpoint', 'context', or 'log'"""
    definition: ToolDefinitionTypedDict
    r"""A tool that can be called from an LLM during the conversation. See https://docs.syllable.ai/Resources/Tools."""
    comments: NotRequired[Nullable[str]]
    r"""Optional comment stored on the tool for this version"""
    deleted_reason: NotRequired[Nullable[str]]
    r"""When operation is delete, reason copied from the tool at delete time"""
    service_name: NotRequired[Nullable[str]]
    r"""Service display name."""


class ToolHistoryResponse(BaseModel):
    r"""API response for one row in GET /tools/{tool_id}/history."""

    tool_id: int
    r"""ID of the tool"""

    version_number: int
    r"""Monotonic version for this tool (1 = oldest)"""

    created_at: datetime
    r"""When this version took effect."""

    updated_by: str
    r"""User who made the change that produced this row"""

    operation: str
    r"""What produced this row: create, update, or delete"""

    service_id: int
    r"""Internal ID of the service this tool belonged to at this version"""

    name: str
    r"""Tool name at this version"""

    description: str
    r"""Human-readable description of the tool at this version"""

    type: str
    r"""Tool type at this version: 'action', 'endpoint', 'context', or 'log'"""

    definition: ToolDefinition
    r"""A tool that can be called from an LLM during the conversation. See https://docs.syllable.ai/Resources/Tools."""

    comments: OptionalNullable[str] = UNSET
    r"""Optional comment stored on the tool for this version"""

    deleted_reason: OptionalNullable[str] = UNSET
    r"""When operation is delete, reason copied from the tool at delete time"""

    service_name: OptionalNullable[str] = UNSET
    r"""Service display name."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["comments", "deleted_reason", "service_name"])
        nullable_fields = set(["comments", "deleted_reason", "service_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
