"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .transcriptwordconfidence import (
    TranscriptWordConfidence,
    TranscriptWordConfidenceTypedDict,
)
from enum import Enum
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import NotRequired, TypedDict


class UtteranceSource(str, Enum):
    PROVIDER = "provider"
    DERIVED_MIN = "derived_min"


class TranscriptConfidenceTypedDict(TypedDict):
    r"""The STT provider's confidence for one user utterance.

    Provenance travels with the score because confidence is NOT comparable across providers:
    Deepgram publishes a genuine acoustic confidence, while Google's proto disclaims the field and
    Chirp 2's documentation states the value \"isn't truly a confidence score\". A bare float read
    without knowing which backend produced it cannot be interpreted.

    `utterance_source` distinguishes a number the provider reported for exactly this text from one
    we computed -- the weakest word, or the weakest across a merged turn. Absent entirely when the
    backend reports nothing, so the transcript flow is unaffected. See ZOO-8595.
    """

    provider: str
    model: NotRequired[Nullable[str]]
    utterance: NotRequired[Nullable[float]]
    utterance_source: NotRequired[Nullable[UtteranceSource]]
    words: NotRequired[Nullable[List[TranscriptWordConfidenceTypedDict]]]
    words_truncated: NotRequired[Nullable[bool]]


class TranscriptConfidence(BaseModel):
    r"""The STT provider's confidence for one user utterance.

    Provenance travels with the score because confidence is NOT comparable across providers:
    Deepgram publishes a genuine acoustic confidence, while Google's proto disclaims the field and
    Chirp 2's documentation states the value \"isn't truly a confidence score\". A bare float read
    without knowing which backend produced it cannot be interpreted.

    `utterance_source` distinguishes a number the provider reported for exactly this text from one
    we computed -- the weakest word, or the weakest across a merged turn. Absent entirely when the
    backend reports nothing, so the transcript flow is unaffected. See ZOO-8595.
    """

    provider: str

    model: OptionalNullable[str] = UNSET

    utterance: OptionalNullable[float] = UNSET

    utterance_source: OptionalNullable[UtteranceSource] = UNSET

    words: OptionalNullable[List[TranscriptWordConfidence]] = UNSET

    words_truncated: OptionalNullable[bool] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["model", "utterance", "utterance_source", "words", "words_truncated"]
        )
        nullable_fields = set(
            ["model", "utterance", "utterance_source", "words", "words_truncated"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
