"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class TwilioChannelConfigUpdateTypedDict(TypedDict):
    r"""Twilio channel config information. If a field is passed as None, it will not be updated."""

    account_sid: NotRequired[Nullable[str]]
    r"""SID of the Twilio account"""
    auth_token: NotRequired[Nullable[str]]
    r"""The Twilio auth token"""


class TwilioChannelConfigUpdate(BaseModel):
    r"""Twilio channel config information. If a field is passed as None, it will not be updated."""

    account_sid: OptionalNullable[str] = UNSET
    r"""SID of the Twilio account"""

    auth_token: OptionalNullable[str] = UNSET
    r"""The Twilio auth token"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_sid", "auth_token"])
        nullable_fields = set(["account_sid", "auth_token"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
