"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .twiliochannelconfigupdate import (
    TwilioChannelConfigUpdate,
    TwilioChannelConfigUpdateTypedDict,
)
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class TwilioChannelUpdateRequestTypedDict(TypedDict):
    r"""Request model for updating a Twilio channel."""

    id: int
    r"""The internal ID of the channel"""
    name: NotRequired[Nullable[str]]
    r"""The name of the channel"""
    config: NotRequired[Nullable[TwilioChannelConfigUpdateTypedDict]]
    r"""The configuration of the channel"""


class TwilioChannelUpdateRequest(BaseModel):
    r"""Request model for updating a Twilio channel."""

    id: int
    r"""The internal ID of the channel"""

    name: OptionalNullable[str] = UNSET
    r"""The name of the channel"""

    config: OptionalNullable[TwilioChannelConfigUpdate] = UNSET
    r"""The configuration of the channel"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "config"])
        nullable_fields = set(["name", "config"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
