"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bridgephrasesconfig import BridgePhrasesConfig, BridgePhrasesConfigTypedDict
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from syllable_sdk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateBridgePhrasesConfigRequestTypedDict(TypedDict):
    bridge_phrases_config: BridgePhrasesConfigTypedDict
    agent_id: NotRequired[Nullable[int]]
    r"""Agent ID to update config for"""
    tool_name: NotRequired[Nullable[str]]
    r"""Tool name to update config for"""


class UpdateBridgePhrasesConfigRequest(BaseModel):
    bridge_phrases_config: Annotated[
        BridgePhrasesConfig,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    agent_id: Annotated[
        OptionalNullable[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Agent ID to update config for"""

    tool_name: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Tool name to update config for"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["agent_id", "tool_name"])
        nullable_fields = set(["agent_id", "tool_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
