"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from syllable_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class WorkflowSessionRowTypedDict(TypedDict):
    r"""One session under a workflow: its execution status plus the insight results,
    grouped by tool name and then by ``insight_key`` in the ``results`` dict.

    A session that is still pending, processing, or failed has an empty
    ``results`` dict; ``status`` and ``error_message`` say why.
    """

    session_id: int
    r"""Session ID"""
    queued_at: datetime
    r"""When the session was queued for this workflow"""
    status: str
    r"""Execution status of this session under the workflow"""
    analyzed_at: NotRequired[Nullable[datetime]]
    r"""When the workflow execution started processing this session; null while the row is still PENDING"""
    error_message: NotRequired[Nullable[str]]
    r"""Error message from the last processing attempt, if any"""
    results: NotRequired[Dict[str, Dict[str, List[Any]]]]
    r"""Results per tool, keyed by tool name then insight_key. Each insight_key holds a list of values: a single value comes back as a one-item list."""


class WorkflowSessionRow(BaseModel):
    r"""One session under a workflow: its execution status plus the insight results,
    grouped by tool name and then by ``insight_key`` in the ``results`` dict.

    A session that is still pending, processing, or failed has an empty
    ``results`` dict; ``status`` and ``error_message`` say why.
    """

    session_id: int
    r"""Session ID"""

    queued_at: datetime
    r"""When the session was queued for this workflow"""

    status: str
    r"""Execution status of this session under the workflow"""

    analyzed_at: OptionalNullable[datetime] = UNSET
    r"""When the workflow execution started processing this session; null while the row is still PENDING"""

    error_message: OptionalNullable[str] = UNSET
    r"""Error message from the last processing attempt, if any"""

    results: Optional[Dict[str, Dict[str, List[Any]]]] = None
    r"""Results per tool, keyed by tool name then insight_key. Each insight_key holds a list of values: a single value comes back as a one-item list."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["analyzed_at", "error_message", "results"])
        nullable_fields = set(["analyzed_at", "error_message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
