workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SyllableSDK:
        inputs:
            - location: openapi.json
        overlays:
            - location: overlay-remove-V1.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/syllable/syllable/syllable-sdk-oas
targets:
    syllable-sdk:
        target: python
        source: SyllableSDK
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/syllable/syllable/code-samples-python-sdk-syllable-sdk-oas-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
