workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    SyllableSDK:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/actiumhealth/actiumhealth/syllable-sdk
targets:
    syllable-sdk:
        target: python
        source: SyllableSDK
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/actiumhealth/actiumhealth/syllable-sdk-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
