"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from syllable_sdk.errors import SyllableSDKError
from syllable_sdk.types import BaseModel
from typing import Optional


class SessionLabelsListBadRequestErrorData(BaseModel):
    detail: str
    r"""A message describing the invalid request"""


@dataclass(unsafe_hash=True)
class SessionLabelsListBadRequestError(SyllableSDKError):
    r"""Bad request, including malformed datetime query parameters"""

    data: SessionLabelsListBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: SessionLabelsListBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
