"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
import httpx
from syllable_sdk.errors import SyllableSDKError
from syllable_sdk.types import BaseModel
from typing import Optional, Union
from typing_extensions import TypeAliasType, TypedDict


class Code(str, Enum):
    r"""Identifies a legacy session link"""

    LEGACY_SESSION_LINK = "legacy_session_link"


class DetailLegacySessionLinkTypedDict(TypedDict):
    code: Code
    r"""Identifies a legacy session link"""
    session_id: str
    r"""The requested transcript ID"""
    redirect_to: str
    r"""The transcript path to open"""
    message: str
    r"""Why this request was rejected"""


class DetailLegacySessionLink(BaseModel):
    code: Code
    r"""Identifies a legacy session link"""

    session_id: str
    r"""The requested transcript ID"""

    redirect_to: str
    r"""The transcript path to open"""

    message: str
    r"""Why this request was rejected"""


DetailTypedDict = TypeAliasType(
    "DetailTypedDict", Union[DetailLegacySessionLinkTypedDict, str]
)
r"""An invalid request message or a legacy transcript link redirect"""


Detail = TypeAliasType("Detail", Union[DetailLegacySessionLink, str])
r"""An invalid request message or a legacy transcript link redirect"""


class SessionsListBadRequestErrorData(BaseModel):
    detail: Detail
    r"""An invalid request message or a legacy transcript link redirect"""


@dataclass(unsafe_hash=True)
class SessionsListBadRequestError(SyllableSDKError):
    r"""Bad request, including malformed datetime query parameters"""

    data: SessionsListBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: SessionsListBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
