name: Auto-Merge PRs from Specific Branches

on:
  pull_request:
    types:
      - opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from a 'speakeasy-sdk-regen*' branch
        id: check-branch
        run: |
          if [[ "${{ github.head_ref }}" == speakeasy-sdk-regen* ]]; then
            echo "Branch matches pattern."
            echo "should_merge=true" >> $GITHUB_ENV
          else
            echo "Branch does not match pattern."
            echo "should_merge=false" >> $GITHUB_ENV
          fi

      - name: Auto-merge PR
        if: env.should_merge == 'true'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
