name: Auto-Merge SDK Regen PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: Auto Merge if PR branch starts with `speakeasy-sdk-regen`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set PR environment variables
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Debug print
        run: |
          echo "PR_NUMBER=$PR_NUMBER"
          echo "SOURCE_BRANCH=$SOURCE_BRANCH"

      - name: Auto-merge if branch matches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$SOURCE_BRANCH" == speakeasy-sdk-regen* ]]; then
            echo "✅ Source branch '$SOURCE_BRANCH' matches. Attempting auto-merge for PR #$PR_NUMBER..."

            # Approve the PR (needed for some protected branches)
            gh pr review "$PR_NUMBER" --approve

            # Enable auto-merge with squash
            gh pr merge "$PR_NUMBER" --auto --squash

          else
            echo "❌ Branch '$SOURCE_BRANCH' does not match pattern. Skipping auto-merge."
          fi
