name: Auto-merge Speakeasy Bot PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  print-actor:
    runs-on: ubuntu-latest
    steps:
      - name: Print Actor Name
        run: echo "GitHub Actor ${{ github.actor }}"

  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'speakeasybot' }}
    steps:
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
